//! 生成物。手で編集しない。
//! 再生成: `python tools/gamedata/import_inkri_targets.py`
//! 系列・費用の割り当ては `tools/gamedata/import_inkri_targets.py` 冒頭のコメント参照。

use super::InkriTarget;
use domain::PartSlot;

pub(super) static INKRI_TARGETS: &[InkriTarget] = &[
    InkriTarget {
        client_item_id: 1023223,
        name: "†地神の兜",
        series: "地神装備",
        part: PartSlot::Helm,
        bianu_seed_cost: Some(15787500),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1023224,
        name: "†地神の背甲",
        series: "地神装備",
        part: PartSlot::Body,
        bianu_seed_cost: Some(15787500),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1023225,
        name: "†地神の目",
        series: "地神装備",
        part: PartSlot::Head,
        bianu_seed_cost: Some(15787500),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1023226,
        name: "†地神の心臓",
        series: "地神装備",
        part: PartSlot::Artifact,
        bianu_seed_cost: Some(15787500),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1023227,
        name: "†地神の具足",
        series: "地神装備",
        part: PartSlot::Leg,
        bianu_seed_cost: Some(15787500),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1023228,
        name: "†地神の指輪",
        series: "地神装備",
        part: PartSlot::Hand,
        bianu_seed_cost: Some(15787500),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1023229,
        name: "†地神の鎧",
        series: "地神装備",
        part: PartSlot::Armor,
        bianu_seed_cost: Some(15787500),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1023231,
        name: "†真・地神の兜",
        series: "地神装備",
        part: PartSlot::Helm,
        bianu_seed_cost: Some(15787500),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1023232,
        name: "†真・地神の背甲",
        series: "地神装備",
        part: PartSlot::Body,
        bianu_seed_cost: Some(15787500),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1023233,
        name: "†真・地神の目",
        series: "地神装備",
        part: PartSlot::Head,
        bianu_seed_cost: Some(15787500),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1023234,
        name: "†真・地神の心臓",
        series: "地神装備",
        part: PartSlot::Artifact,
        bianu_seed_cost: Some(15787500),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1023235,
        name: "†真・地神の具足",
        series: "地神装備",
        part: PartSlot::Leg,
        bianu_seed_cost: Some(15787500),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1023236,
        name: "†真・地神の指輪",
        series: "地神装備",
        part: PartSlot::Hand,
        bianu_seed_cost: Some(15787500),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1023237,
        name: "†真・地神の鎧",
        series: "地神装備",
        part: PartSlot::Armor,
        bianu_seed_cost: Some(15787500),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1029378,
        name: "†モモンズ・グリーブ",
        series: "モモンズ・グリーブ",
        part: PartSlot::Leg,
        bianu_seed_cost: Some(3000000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039515,
        name: "†アクィルスレイピア",
        series: "アクィルス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(10500000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039516,
        name: "†アクィルスソード",
        series: "アクィルス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(10500000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039517,
        name: "†アクィルスシミター",
        series: "アクィルス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(10500000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039518,
        name: "†アクィルスフェイクソード",
        series: "アクィルス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(10500000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039519,
        name: "†アクィルスブレイド",
        series: "アクィルス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(10500000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039520,
        name: "†アクィルススティック",
        series: "アクィルス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(10500000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039521,
        name: "†アクィルススピア",
        series: "アクィルス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(10500000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039522,
        name: "†アクィルスウィップ",
        series: "アクィルス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(10500000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039523,
        name: "†アクィルスフレイル",
        series: "アクィルス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(10500000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039524,
        name: "†アクィルススタッフ",
        series: "アクィルス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(10500000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039525,
        name: "†アクィルスロッド",
        series: "アクィルス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(10500000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039526,
        name: "†アクィルスメイス",
        series: "アクィルス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(10500000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039527,
        name: "†アクィルスダガー",
        series: "アクィルス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(10500000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039528,
        name: "†アクィルスナイフ",
        series: "アクィルス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(10500000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039529,
        name: "†アクィルスアックス",
        series: "アクィルス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(10500000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039530,
        name: "†アクィルススモールソード",
        series: "アクィルス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(10500000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039531,
        name: "†アクィルスワンド",
        series: "アクィルス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(10500000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039532,
        name: "†アクィルスピストル",
        series: "アクィルス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(10500000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039533,
        name: "†アクィルスマナピストル",
        series: "アクィルス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(10500000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039534,
        name: "†アクィルスカーラ",
        series: "アクィルス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(10500000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039535,
        name: "†アクィルスクロー",
        series: "アクィルス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(10500000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039536,
        name: "†アクィルスセプター",
        series: "アクィルス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(10500000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039537,
        name: "†アクィルスハンドベル",
        series: "アクィルス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(10500000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039538,
        name: "†アクィルスグラディウス",
        series: "アクィルス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(10500000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039539,
        name: "†アクィルスグラディウス(Sub)",
        series: "アクィルス",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(11250000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039540,
        name: "†アクィルスクリス",
        series: "アクィルス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(10500000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039541,
        name: "†アクィルスクリス(Sub)",
        series: "アクィルス",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(11250000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039542,
        name: "†アクィルスサイズ",
        series: "アクィルス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(10500000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039543,
        name: "†アクィルスハンマー",
        series: "アクィルス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(10500000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039544,
        name: "†アクィルストーテム",
        series: "アクィルス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(10500000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039545,
        name: "†アクィルスハンドランチャー",
        series: "アクィルス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(10500000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039546,
        name: "†アクィルスアーミングソード",
        series: "アクィルス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(10500000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039547,
        name: "†アクィルスメイル",
        series: "アクィルス",
        part: PartSlot::Armor,
        bianu_seed_cost: Some(11250000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039548,
        name: "†アクィルスアーマー",
        series: "アクィルス",
        part: PartSlot::Armor,
        bianu_seed_cost: Some(11250000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039549,
        name: "†アクィルスローブ",
        series: "アクィルス",
        part: PartSlot::Armor,
        bianu_seed_cost: Some(11250000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039550,
        name: "†アクィルススーツ",
        series: "アクィルス",
        part: PartSlot::Armor,
        bianu_seed_cost: Some(11250000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039551,
        name: "†アクィルスリフレクトアーマー",
        series: "アクィルス",
        part: PartSlot::Armor,
        bianu_seed_cost: Some(11250000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039552,
        name: "†アクィルスリスト",
        series: "アクィルス",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(11250000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039553,
        name: "†アクィルスバングル",
        series: "アクィルス",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(11250000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039554,
        name: "†アクィルスバンド",
        series: "アクィルス",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(11250000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039555,
        name: "†アクィルスシールド",
        series: "アクィルス",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(11250000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039556,
        name: "†アクィルスクリスタル",
        series: "アクィルス",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(11250000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039557,
        name: "†アクィルススペルブック",
        series: "アクィルス",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(11250000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039558,
        name: "†アクィルスマガジン",
        series: "アクィルス",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(11250000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039559,
        name: "†アクィルスマナマガジン",
        series: "アクィルス",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(11250000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039560,
        name: "†アクィルスペンデュラム",
        series: "アクィルス",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(11250000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039561,
        name: "†アクィルスガントレット",
        series: "アクィルス",
        part: PartSlot::Hand,
        bianu_seed_cost: Some(9000000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039562,
        name: "†アクィルスヘルム",
        series: "アクィルス",
        part: PartSlot::Helm,
        bianu_seed_cost: Some(11250000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039563,
        name: "†アクィルスアミュレット",
        series: "アクィルス",
        part: PartSlot::Head,
        bianu_seed_cost: Some(9000000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039564,
        name: "†アクィルスウィング",
        series: "アクィルス",
        part: PartSlot::Body,
        bianu_seed_cost: Some(8250000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1039565,
        name: "†アクィルスブーツ",
        series: "アクィルス",
        part: PartSlot::Leg,
        bianu_seed_cost: Some(9000000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1040995,
        name: "†アビスレイピア",
        series: "アビス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(11325000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1040996,
        name: "†アビスソード",
        series: "アビス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(11325000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1040997,
        name: "†アビスシミター",
        series: "アビス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(11325000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1040998,
        name: "†アビスフェイクソード",
        series: "アビス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(11325000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1040999,
        name: "†アビスブレード",
        series: "アビス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(11325000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041000,
        name: "†アビススティック",
        series: "アビス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(11325000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041001,
        name: "†アビススピア",
        series: "アビス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(11325000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041002,
        name: "†アビスウィップ",
        series: "アビス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(11325000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041003,
        name: "†アビスフレイル",
        series: "アビス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(11325000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041004,
        name: "†アビススタッフ",
        series: "アビス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(11325000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041005,
        name: "†アビスロッド",
        series: "アビス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(11325000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041006,
        name: "†アビスメイス",
        series: "アビス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(11325000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041007,
        name: "†アビスダガー",
        series: "アビス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(11325000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041008,
        name: "†アビスナイフ",
        series: "アビス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(11325000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041009,
        name: "†アビスアックス",
        series: "アビス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(11325000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041010,
        name: "†アビススモールソード",
        series: "アビス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(11325000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041011,
        name: "†アビスワンド",
        series: "アビス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(11325000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041012,
        name: "†アビスピストル",
        series: "アビス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(11325000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041013,
        name: "†アビスマナピストル",
        series: "アビス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(11325000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041014,
        name: "†アビスカーラ",
        series: "アビス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(11325000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041015,
        name: "†アビスクロー",
        series: "アビス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(11325000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041016,
        name: "†アビスセプター",
        series: "アビス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(11325000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041017,
        name: "†アビスハンドベル",
        series: "アビス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(11325000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041018,
        name: "†アビスグラディウス",
        series: "アビス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(11325000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041019,
        name: "†アビスグラディウス(Sub)",
        series: "アビス",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(12075000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041020,
        name: "†アビスクリス",
        series: "アビス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(11325000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041021,
        name: "†アビスクリス(Sub)",
        series: "アビス",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(12075000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041022,
        name: "†アビスサイズ",
        series: "アビス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(11325000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041023,
        name: "†アビスハンマー",
        series: "アビス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(11325000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041024,
        name: "†アビストーテム",
        series: "アビス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(11325000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041025,
        name: "†アビスハンドランチャー",
        series: "アビス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(11325000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041026,
        name: "†アビスアーミングソード",
        series: "アビス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(11325000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041027,
        name: "†アビスメイル",
        series: "アビス",
        part: PartSlot::Armor,
        bianu_seed_cost: Some(12075000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041028,
        name: "†アビスアーマー",
        series: "アビス",
        part: PartSlot::Armor,
        bianu_seed_cost: Some(12075000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041029,
        name: "†アビスローブ",
        series: "アビス",
        part: PartSlot::Armor,
        bianu_seed_cost: Some(12075000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041030,
        name: "†アビススーツ",
        series: "アビス",
        part: PartSlot::Armor,
        bianu_seed_cost: Some(12075000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041031,
        name: "†アビスリフレクトアーマー",
        series: "アビス",
        part: PartSlot::Armor,
        bianu_seed_cost: Some(12075000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041032,
        name: "†アビスリスト",
        series: "アビス",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(12075000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041033,
        name: "†アビスバングル",
        series: "アビス",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(12075000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041034,
        name: "†アビスバンド",
        series: "アビス",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(12075000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041035,
        name: "†アビスシールド",
        series: "アビス",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(12075000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041036,
        name: "†アビスクリスタル",
        series: "アビス",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(12075000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041037,
        name: "†アビススペルブック",
        series: "アビス",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(12075000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041038,
        name: "†アビスマガジン",
        series: "アビス",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(12075000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041039,
        name: "†アビスマジカルマガジン",
        series: "アビス",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(12075000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041040,
        name: "†アビスペンデュラム",
        series: "アビス",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(12075000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041041,
        name: "†アビスガントレット",
        series: "アビス",
        part: PartSlot::Hand,
        bianu_seed_cost: Some(10575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041042,
        name: "†アビスヘルム",
        series: "アビス",
        part: PartSlot::Helm,
        bianu_seed_cost: Some(12075000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041043,
        name: "†アビスアミュレット",
        series: "アビス",
        part: PartSlot::Head,
        bianu_seed_cost: Some(10575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041044,
        name: "†アビスウィング",
        series: "アビス",
        part: PartSlot::Body,
        bianu_seed_cost: Some(8325000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1041045,
        name: "†アビスブーツ",
        series: "アビス",
        part: PartSlot::Leg,
        bianu_seed_cost: Some(10575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044260,
        name: "†エクリプスレイピア",
        series: "エクリプス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044261,
        name: "†エクリプスソード",
        series: "エクリプス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044262,
        name: "†エクリプスシミター",
        series: "エクリプス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044263,
        name: "†エクリプスフェイクソード",
        series: "エクリプス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044264,
        name: "†エクリプスブレード",
        series: "エクリプス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044265,
        name: "†エクリプススティック",
        series: "エクリプス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044266,
        name: "†エクリプススピア",
        series: "エクリプス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044267,
        name: "†エクリプスウィップ",
        series: "エクリプス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044268,
        name: "†エクリプスフレイル",
        series: "エクリプス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044269,
        name: "†エクリプススタッフ",
        series: "エクリプス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044270,
        name: "†エクリプスロッド",
        series: "エクリプス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044271,
        name: "†エクリプスメイス",
        series: "エクリプス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044272,
        name: "†エクリプスダガー",
        series: "エクリプス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044273,
        name: "†エクリプスナイフ",
        series: "エクリプス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044274,
        name: "†エクリプスアックス",
        series: "エクリプス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044275,
        name: "†エクリプススモールソード",
        series: "エクリプス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044276,
        name: "†エクリプスワンド",
        series: "エクリプス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044277,
        name: "†エクリプスピストル",
        series: "エクリプス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044278,
        name: "†エクリプスマナピストル",
        series: "エクリプス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044279,
        name: "†エクリプスカーラ",
        series: "エクリプス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044280,
        name: "†エクリプスクロー",
        series: "エクリプス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044281,
        name: "†エクリプスセプター",
        series: "エクリプス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044282,
        name: "†エクリプスハンドベル",
        series: "エクリプス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044283,
        name: "†エクリプスグラディウス",
        series: "エクリプス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044284,
        name: "†エクリプスグラディウス(Sub)",
        series: "エクリプス",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044285,
        name: "†エクリプスクリス",
        series: "エクリプス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044286,
        name: "†エクリプスクリス(Sub)",
        series: "エクリプス",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044287,
        name: "†エクリプスサイズ",
        series: "エクリプス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044288,
        name: "†エクリプスハンマー",
        series: "エクリプス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044289,
        name: "†エクリプストーテム",
        series: "エクリプス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044290,
        name: "†エクリプスハンドランチャー",
        series: "エクリプス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044291,
        name: "†エクリプスアーミングソード",
        series: "エクリプス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044292,
        name: "†エクリプスメイル",
        series: "エクリプス",
        part: PartSlot::Armor,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044293,
        name: "†エクリプスアーマー",
        series: "エクリプス",
        part: PartSlot::Armor,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044294,
        name: "†エクリプスローブ",
        series: "エクリプス",
        part: PartSlot::Armor,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044295,
        name: "†エクリプススーツ",
        series: "エクリプス",
        part: PartSlot::Armor,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044296,
        name: "†エクリプスリフレクトアーマー",
        series: "エクリプス",
        part: PartSlot::Armor,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044297,
        name: "†エクリプスリスト",
        series: "エクリプス",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044298,
        name: "†エクリプスバングル",
        series: "エクリプス",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044299,
        name: "†エクリプスバンド",
        series: "エクリプス",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044300,
        name: "†エクリプスシールド",
        series: "エクリプス",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044301,
        name: "†エクリプスクリスタル",
        series: "エクリプス",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044302,
        name: "†エクリプススペルブック",
        series: "エクリプス",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044303,
        name: "†エクリプスマガジン",
        series: "エクリプス",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044304,
        name: "†エクリプスマジカルマガジン",
        series: "エクリプス",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044305,
        name: "†エクリプスペンデュラム",
        series: "エクリプス",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044306,
        name: "†エクリプスガントレット",
        series: "エクリプス",
        part: PartSlot::Hand,
        bianu_seed_cost: Some(14325000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044307,
        name: "†エクリプスヘルム",
        series: "エクリプス",
        part: PartSlot::Helm,
        bianu_seed_cost: Some(25575000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044308,
        name: "†エクリプスアミュレット",
        series: "エクリプス",
        part: PartSlot::Head,
        bianu_seed_cost: Some(14325000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044309,
        name: "†エクリプスウィング",
        series: "エクリプス",
        part: PartSlot::Body,
        bianu_seed_cost: Some(14325000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1044310,
        name: "†エクリプスブーツ",
        series: "エクリプス",
        part: PartSlot::Leg,
        bianu_seed_cost: Some(14325000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1045792,
        name: "†アクィルスソードシェイプ",
        series: "アクィルス",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(10500000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1060030,
        name: "†尖ったネニャフル学院のメイル",
        series: "ネニャフル学院の鎧",
        part: PartSlot::Armor,
        bianu_seed_cost: Some(28650000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1060031,
        name: "†尖ったネニャフル学院のアーマー",
        series: "ネニャフル学院の鎧",
        part: PartSlot::Armor,
        bianu_seed_cost: Some(28650000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1060032,
        name: "†尖ったネニャフル学院のローブ",
        series: "ネニャフル学院の鎧",
        part: PartSlot::Armor,
        bianu_seed_cost: Some(28650000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1060033,
        name: "†尖ったネニャフル学院のスーツ",
        series: "ネニャフル学院の鎧",
        part: PartSlot::Armor,
        bianu_seed_cost: Some(28650000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1060034,
        name: "†鋭いネニャフル学院のメイル",
        series: "ネニャフル学院の鎧",
        part: PartSlot::Armor,
        bianu_seed_cost: Some(28650000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1060035,
        name: "†鋭いネニャフル学院のアーマー",
        series: "ネニャフル学院の鎧",
        part: PartSlot::Armor,
        bianu_seed_cost: Some(28650000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1060036,
        name: "†鋭いネニャフル学院のローブ",
        series: "ネニャフル学院の鎧",
        part: PartSlot::Armor,
        bianu_seed_cost: Some(28650000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1060037,
        name: "†鋭いネニャフル学院のスーツ",
        series: "ネニャフル学院の鎧",
        part: PartSlot::Armor,
        bianu_seed_cost: Some(28650000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1060038,
        name: "†冴えたネニャフル学院のメイル",
        series: "ネニャフル学院の鎧",
        part: PartSlot::Armor,
        bianu_seed_cost: Some(28650000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1060039,
        name: "†冴えたネニャフル学院のアーマー",
        series: "ネニャフル学院の鎧",
        part: PartSlot::Armor,
        bianu_seed_cost: Some(28650000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1060040,
        name: "†冴えたネニャフル学院のローブ",
        series: "ネニャフル学院の鎧",
        part: PartSlot::Armor,
        bianu_seed_cost: Some(28650000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1060041,
        name: "†冴えたネニャフル学院のスーツ",
        series: "ネニャフル学院の鎧",
        part: PartSlot::Armor,
        bianu_seed_cost: Some(28650000),
        eta_seed_cost: None,
    },
    InkriTarget {
        client_item_id: 1060370,
        name: "†セイクリッドレイピア",
        series: "セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060371,
        name: "†セイクリッドソード",
        series: "セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060372,
        name: "†セイクリッドシミター",
        series: "セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060373,
        name: "†セイクリッドフェイクソード",
        series: "セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060374,
        name: "†セイクリッドブレード",
        series: "セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060375,
        name: "†セイクリッドスティック",
        series: "セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060376,
        name: "†セイクリッドスピア",
        series: "セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060377,
        name: "†セイクリッドウィップ",
        series: "セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060378,
        name: "†セイクリッドフレイル",
        series: "セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060379,
        name: "†セイクリッドスタッフ",
        series: "セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060380,
        name: "†セイクリッドロッド",
        series: "セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060381,
        name: "†セイクリッドメイス",
        series: "セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060382,
        name: "†セイクリッドダガー",
        series: "セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060383,
        name: "†セイクリッドナイフ",
        series: "セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060384,
        name: "†セイクリッドアックス",
        series: "セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060385,
        name: "†セイクリッドスモールソード",
        series: "セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060386,
        name: "†セイクリッドワンド",
        series: "セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060387,
        name: "†セイクリッドピストル",
        series: "セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060388,
        name: "†セイクリッドマナピストル",
        series: "セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060389,
        name: "†セイクリッドカーラ",
        series: "セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060390,
        name: "†セイクリッドクロー",
        series: "セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060391,
        name: "†セイクリッドセプター",
        series: "セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060392,
        name: "†セイクリッドハンドベル",
        series: "セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060393,
        name: "†セイクリッドグラディウス",
        series: "セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060394,
        name: "†セイクリッドグラディウス(Sub)",
        series: "セイクリッド",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060395,
        name: "†セイクリッドクリス",
        series: "セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060396,
        name: "†セイクリッドクリス(Sub)",
        series: "セイクリッド",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060397,
        name: "†セイクリッドサイズ",
        series: "セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060398,
        name: "†セイクリッドハンマー",
        series: "セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060399,
        name: "†セイクリッドトーテム",
        series: "セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060400,
        name: "†セイクリッドハンドランチャー",
        series: "セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060401,
        name: "†セイクリッドアーミングソード",
        series: "セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060402,
        name: "†セイクリッドソードシェイプ",
        series: "セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060403,
        name: "†セイクリッドメイル",
        series: "セイクリッド",
        part: PartSlot::Armor,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060404,
        name: "†セイクリッドアーマー",
        series: "セイクリッド",
        part: PartSlot::Armor,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060405,
        name: "†セイクリッドローブ",
        series: "セイクリッド",
        part: PartSlot::Armor,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060406,
        name: "†セイクリッドスーツ",
        series: "セイクリッド",
        part: PartSlot::Armor,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060407,
        name: "†セイクリッドリフレクトアーマー",
        series: "セイクリッド",
        part: PartSlot::Armor,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060408,
        name: "†セイクリッドリスト",
        series: "セイクリッド",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060409,
        name: "†セイクリッドバングル",
        series: "セイクリッド",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060410,
        name: "†セイクリッドバンド",
        series: "セイクリッド",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060411,
        name: "†セイクリッドシールド",
        series: "セイクリッド",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060412,
        name: "†セイクリッドクリスタル",
        series: "セイクリッド",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060413,
        name: "†セイクリッドスペルブック",
        series: "セイクリッド",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060414,
        name: "†セイクリッドマガジン",
        series: "セイクリッド",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060415,
        name: "†セイクリッドマジカルマガジン",
        series: "セイクリッド",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060416,
        name: "†セイクリッドペンデュラム",
        series: "セイクリッド",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060417,
        name: "†セイクリッドガントレット",
        series: "セイクリッド",
        part: PartSlot::Hand,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060418,
        name: "†セイクリッドヘルム",
        series: "セイクリッド",
        part: PartSlot::Helm,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060419,
        name: "†セイクリッドアミュレット",
        series: "セイクリッド",
        part: PartSlot::Head,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060420,
        name: "†セイクリッドマント",
        series: "セイクリッド",
        part: PartSlot::Body,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060421,
        name: "†セイクリッドブーツ",
        series: "セイクリッド",
        part: PartSlot::Leg,
        bianu_seed_cost: Some(36825000),
        eta_seed_cost: Some(296680000),
    },
    InkriTarget {
        client_item_id: 1060794,
        name: "†改・セイクリッドレイピア",
        series: "改・セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060795,
        name: "†改・セイクリッドソード",
        series: "改・セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060796,
        name: "†改・セイクリッドシミター",
        series: "改・セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060797,
        name: "†改・セイクリッドフェイクソード",
        series: "改・セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060798,
        name: "†改・セイクリッドブレード",
        series: "改・セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060799,
        name: "†改・セイクリッドスティック",
        series: "改・セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060800,
        name: "†改・セイクリッドスピア",
        series: "改・セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060801,
        name: "†改・セイクリッドウィップ",
        series: "改・セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060802,
        name: "†改・セイクリッドフレイル",
        series: "改・セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060803,
        name: "†改・セイクリッドスタッフ",
        series: "改・セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060804,
        name: "†改・セイクリッドロッド",
        series: "改・セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060805,
        name: "†改・セイクリッドメイス",
        series: "改・セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060806,
        name: "†改・セイクリッドダガー",
        series: "改・セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060807,
        name: "†改・セイクリッドナイフ",
        series: "改・セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060808,
        name: "†改・セイクリッドアックス",
        series: "改・セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060809,
        name: "†改・セイクリッドスモールソード",
        series: "改・セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060810,
        name: "†改・セイクリッドワンド",
        series: "改・セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060811,
        name: "†改・セイクリッドピストル",
        series: "改・セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060812,
        name: "†改・セイクリッドマナピストル",
        series: "改・セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060813,
        name: "†改・セイクリッドカーラ",
        series: "改・セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060814,
        name: "†改・セイクリッドクロー",
        series: "改・セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060815,
        name: "†改・セイクリッドセプター",
        series: "改・セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060816,
        name: "†改・セイクリッドハンドベル",
        series: "改・セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060817,
        name: "†改・セイクリッドグラディウス",
        series: "改・セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060818,
        name: "†改・セイクリッドグラディウス(Sub)",
        series: "改・セイクリッド",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060819,
        name: "†改・セイクリッドクリス",
        series: "改・セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060820,
        name: "†改・セイクリッドクリス(Sub)",
        series: "改・セイクリッド",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060821,
        name: "†改・セイクリッドサイズ",
        series: "改・セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060822,
        name: "†改・セイクリッドハンマー",
        series: "改・セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060823,
        name: "†改・セイクリッドトーテム",
        series: "改・セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060824,
        name: "†改・セイクリッドハンドランチャー",
        series: "改・セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060825,
        name: "†改・セイクリッドアーミングソード",
        series: "改・セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060826,
        name: "†改・セイクリッドソードシェイプ",
        series: "改・セイクリッド",
        part: PartSlot::Weapon,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060827,
        name: "†改・セイクリッドメイル",
        series: "改・セイクリッド",
        part: PartSlot::Armor,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060828,
        name: "†改・セイクリッドアーマー",
        series: "改・セイクリッド",
        part: PartSlot::Armor,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060829,
        name: "†改・セイクリッドローブ",
        series: "改・セイクリッド",
        part: PartSlot::Armor,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060830,
        name: "†改・セイクリッドスーツ",
        series: "改・セイクリッド",
        part: PartSlot::Armor,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060831,
        name: "†改・セイクリッドリフレクトアーマー",
        series: "改・セイクリッド",
        part: PartSlot::Armor,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060832,
        name: "†改・セイクリッドリスト",
        series: "改・セイクリッド",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060833,
        name: "†改・セイクリッドバングル",
        series: "改・セイクリッド",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060834,
        name: "†改・セイクリッドバンド",
        series: "改・セイクリッド",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060835,
        name: "†改・セイクリッドシールド",
        series: "改・セイクリッド",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060836,
        name: "†改・セイクリッドクリスタル",
        series: "改・セイクリッド",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060837,
        name: "†改・セイクリッドスペルブック",
        series: "改・セイクリッド",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060838,
        name: "†改・セイクリッドマガジン",
        series: "改・セイクリッド",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060839,
        name: "†改・セイクリッドマジカルマガジン",
        series: "改・セイクリッド",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060840,
        name: "†改・セイクリッドペンデュラム",
        series: "改・セイクリッド",
        part: PartSlot::Shield,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060841,
        name: "†改・セイクリッドガントレット",
        series: "改・セイクリッド",
        part: PartSlot::Hand,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060842,
        name: "†改・セイクリッドヘルム",
        series: "改・セイクリッド",
        part: PartSlot::Helm,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060843,
        name: "†改・セイクリッドアミュレット",
        series: "改・セイクリッド",
        part: PartSlot::Head,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060844,
        name: "†改・セイクリッドマント",
        series: "改・セイクリッド",
        part: PartSlot::Body,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
    InkriTarget {
        client_item_id: 1060845,
        name: "†改・セイクリッドブーツ",
        series: "改・セイクリッド",
        part: PartSlot::Leg,
        bianu_seed_cost: Some(38700000),
        eta_seed_cost: Some(313680000),
    },
];
