//! マスタリーのカタログ(wiki: 各キャラの Skill ページの「マスタリースキル」表。取得 2026-08-27)。
//!
//! **段ごとに 3 択で 1 つだけ選ぶ。**段の数はキャラによって違う(3〜5 段。リーチェだけ 15 段)。
//! 同じ段の選択肢は効き先がばらばらなので、計算に入らないもの(防御側・確率発動・条件付き・
//! スキルの入れ替え)も `RecordOnly` として収録する。選べないと「その段で何を取ったか」が
//! 表せず、取っていない選択肢との区別も付かない。
//!
//! **id は wiki の表の位置そのまま**(`<キャラ>_m<段>_<1..3>`)。243 件の日本語名をローマ字に
//! すると読みを確かめられず、まちがえても気づけない。表の No. 列が段、モード列
//! (Primary / Secondary / Tertiary。ベンヤだけ DEATH / BLOOD / DEFENCE)が 1..3 の並び。
//!
//! **数値は同じページの「スキル性能一覧」を正とする。**この「マスタリースキル」の節には
//! **更新から取り残された古い値が混ざっている**(シベリン【暴走】は性能表 +20% に対しここは
//! +60%、ジョシュア【アノーイングネイバー】は +3% に対し +10%)。ただし全部が古いわけではなく
//! (ボリス【シルバースカル優勝者】は Ver8.20 の更新が反映済み)、**追随度は行ごとに違う**。
//! 解説が長い形で入っているのでこの節から取り込むが、**計算に入れる数値は必ず性能一覧と
//! 突き合わせる**。突き合わせ済みなのは下の「計算に入るのは12件」だけ。
//!
//! **効き先は「無条件で言い切っているものだけ」計算に入れる。**「〈スノーガード〉使用中」
//! 「スキルを選択」「確率で」のような条件付きは、条件を持っていないので `RecordOnly` にする。
//! 誤って計算に入れるほうが、入れないより害が大きい(数字が黙ってずれる)。
//! 243 件中 11 件だけがモデル済み。
//!
//! **スキルの性能を書き換えるマスタリー**(ミラ【グッドフェイス】、マキシミンの M3 三択、
//! ロアミニ M3【ア・プチ】【パウアトゥン】、ジョシュア M2【エリート】)は、ここでは
//! `RecordOnly` のままにする。効果は `character_skills.rs` のスキル側が
//! `mastery_overrides` として持つ(両方に持たせると二重に数える)。
//!
//! **アナイスは未収録** — wiki の Skill/アナイス にマスタリーの節が無い(コメントアウトされている)。

use domain::{DamageCategory, MasteryDef, SkillEffect, StatKind, StatLayer};

use crate::Source;

pub const MASTERY_SOURCE: Source = Source {
    page: "各キャラの Skill ページ「マスタリースキル」",
    retrieved_on: "2026-08-27",
    note: "18 キャラ 243 件(アナイスは wiki に節が無く未収録)。効き先は無条件のものだけ収録し、条件付きは記録のみ",
};

const HACK_DEF: &[StatKind] = &[StatKind::Hack, StatKind::Def];

const MASTERIES: &[MasteryDef] = &[
    // --- benya
    MasteryDef {
        id: "benya_m1_1",
        game_character_id: "benya",
        tier: 1,
        name: "フィア・オブ・ブラッド",
        effect: SkillEffect::RecordOnly,
        note: "[極・カース・オブ・ブラッド] 命中率が上昇する。攻撃された対象は黒属性が低下する。（30秒持続）",
    },
    MasteryDef {
        id: "benya_m1_2",
        game_character_id: "benya",
        tier: 1,
        name: "スチールフォーアス",
        effect: SkillEffect::RecordOnly,
        note: "[極・ソウルスチール]の最大HP回復量が増加し、発動時に周囲のチームメンバーも一緒に回復する。また、黒属性が増加する",
    },
    MasteryDef {
        id: "benya_m1_3",
        game_character_id: "benya",
        tier: 1,
        name: "アクティブカウンター",
        effect: SkillEffect::RecordOnly,
        note: "[極・スピンハンマー]でダメージを与えたとき、一定確率で[カウンターハンマー活性化]バフが付く",
    },
    MasteryDef {
        id: "benya_m2_1",
        game_character_id: "benya",
        tier: 2,
        name: "インベージョンブラッド",
        effect: SkillEffect::RecordOnly,
        note: "[極・カース・オブ・ブラッド]の持続ダメージが増加する。",
    },
    MasteryDef {
        id: "benya_m2_2",
        game_character_id: "benya",
        tier: 2,
        name: "インフェクションブラッド",
        effect: SkillEffect::RecordOnly,
        note: "一部スキルに[極・出血]([MR]依存,50%,Cri2x,10s持続,3.3s間隔)が追加発動する。",
    },
    MasteryDef {
        id: "benya_m2_3",
        game_character_id: "benya",
        tier: 2,
        name: "リフレクション",
        effect: SkillEffect::RecordOnly,
        note: "[極・アイアンメイデン]や[極・アイアン・バディーズ]発動時に[カウンターハンマー活性化]バフ発動率が増加する。",
    },
    MasteryDef {
        id: "benya_m3_1",
        game_character_id: "benya",
        tier: 3,
        name: "ハードディフェンス",
        effect: SkillEffect::RecordOnly,
        note: "[極・アイアン・メイデン]被ダメージ60%減少",
    },
    MasteryDef {
        id: "benya_m3_2",
        game_character_id: "benya",
        tier: 3,
        name: "アイアン・バディーズ",
        effect: SkillEffect::RecordOnly,
        note: "[極・アイアンメイデン]を[極・アイアン・バディーズ]に変更する。",
    },
    MasteryDef {
        id: "benya_m3_3",
        game_character_id: "benya",
        tier: 3,
        name: "アボイドディメンション",
        effect: SkillEffect::RecordOnly,
        note: "[極・ソウルフォーメーション]回避効果が発動する。",
    },
    MasteryDef {
        id: "benya_m4_1",
        game_character_id: "benya",
        tier: 4,
        name: "トランススピリット",
        effect: SkillEffect::RecordOnly,
        note: "[極・トランススピリット] スキルを選択 攻撃ダメージ+10%",
    },
    MasteryDef {
        id: "benya_m4_2",
        game_character_id: "benya",
        tier: 4,
        name: "アルトリスティックスピリット",
        effect: SkillEffect::RecordOnly,
        note: "[極・アルトリスティックスピリット] スキルを選択 自身の攻撃ダメージ+7%、チームメンバーの攻撃ダメージ+5%",
    },
    MasteryDef {
        id: "benya_m4_3",
        game_character_id: "benya",
        tier: 4,
        name: "ハーモニックスピリット",
        effect: SkillEffect::RecordOnly,
        note: "[極・ハーモニックスピリット] スキルを選択 攻撃ダメージ+7%/最小命中率+10%",
    },
    // --- boris
    MasteryDef {
        id: "boris_m1_1",
        game_character_id: "boris",
        tier: 1,
        name: "一閃",
        effect: SkillEffect::ActualDelay { percent: 5.0 },
        note: "中ディレイが5％減少する。共通スキル<フルスロットル>と重複が可能。",
    },
    MasteryDef {
        id: "boris_m1_2",
        game_character_id: "boris",
        tier: 1,
        name: "斬撃",
        effect: SkillEffect::Damage {
                category: DamageCategory::AttackDamageSkill,
                percent: 2.0,
            },
        note: "攻撃ダメージ増加（+2%)",
    },
    MasteryDef {
        id: "boris_m1_3",
        game_character_id: "boris",
        tier: 1,
        name: "一撃",
        effect: SkillEffect::RecordOnly,
        note: "攻撃スキルを使用すると、防御無視攻撃が確率で出る。(15%)",
    },
    MasteryDef {
        id: "boris_m2_1",
        game_character_id: "boris",
        tier: 2,
        name: "抗争の生存者",
        effect: SkillEffect::RecordOnly,
        note: "被ダメージ減少(-3%)",
    },
    MasteryDef {
        id: "boris_m2_2",
        game_character_id: "boris",
        tier: 2,
        name: "必滅者",
        effect: SkillEffect::RecordOnly,
        note: "攻撃ダメージ増加(+3%)",
    },
    MasteryDef {
        id: "boris_m2_3",
        game_character_id: "boris",
        tier: 2,
        name: "シルバースカル優勝者",
        effect: SkillEffect::StatRate {
            stats: HACK_DEF,
            percent: 10.0,
            layer: StatLayer::MultiplierB,
        },
        note: "HACK+10%、DEF+10%",
    },
    MasteryDef {
        id: "boris_m3_1",
        game_character_id: "boris",
        tier: 3,
        name: "インデュア",
        effect: SkillEffect::RecordOnly,
        note: "<スノーガード>使用中、被ダメージ減少(-7%)",
    },
    MasteryDef {
        id: "boris_m3_2",
        game_character_id: "boris",
        tier: 3,
        name: "スイッチング",
        effect: SkillEffect::RecordOnly,
        note: "<スノーガード>使用中、被ダメージ比1%のSP回復",
    },
    MasteryDef {
        id: "boris_m3_3",
        game_character_id: "boris",
        tier: 3,
        name: "騎士道",
        effect: SkillEffect::RecordOnly,
        note: "<スノーガード>使用中、被ダメージ毎に<騎士道>バフが増加し、30になると攻撃ダメージ/被ダメージ増加(+3%、持続30s)",
    },
    MasteryDef {
        id: "boris_m4_1",
        game_character_id: "boris",
        tier: 4,
        name: "剣を扱う技術",
        effect: SkillEffect::StatRate {
            stats: HACK_DEF,
            percent: 10.0,
            layer: StatLayer::MultiplierB,
        },
        note: "HACK+10%、DEF+10%",
    },
    MasteryDef {
        id: "boris_m4_2",
        game_character_id: "boris",
        tier: 4,
        name: "冬を降らせる子",
        effect: SkillEffect::RecordOnly,
        note: "<霜>状態の対象に攻撃すると追加ダメージ(+10%)",
    },
    MasteryDef {
        id: "boris_m4_3",
        game_character_id: "boris",
        tier: 4,
        name: "冷酷で絶対的な審判者",
        effect: SkillEffect::Damage {
                category: DamageCategory::AttackDamageSkill,
                percent: 2.0,
            },
        note: "攻撃ダメージ増加(+2%)",
    },
    // --- chloe
    MasteryDef {
        id: "chloe_m1_1",
        game_character_id: "chloe",
        tier: 1,
        name: "スタビライジング",
        effect: SkillEffect::RecordOnly,
        note: "マナウォール使用中、被ダメージ減少(-5%)",
    },
    MasteryDef {
        id: "chloe_m1_2",
        game_character_id: "chloe",
        tier: 1,
        name: "コンバージョン",
        effect: SkillEffect::RecordOnly,
        note: "マナウォール使用中、攻撃を受けた際に被ダメージに比例してMP回復",
    },
    MasteryDef {
        id: "chloe_m1_3",
        game_character_id: "chloe",
        tier: 1,
        name: "リバウンド",
        effect: SkillEffect::RecordOnly,
        note: "マナウォール使用中、被ダメージ毎に<チャージドエネルギー>バフが増加し、 10になるとバフを消費して攻撃スキル使用時に追加ダメージ(+100%)を与える",
    },
    MasteryDef {
        id: "chloe_m2_1",
        game_character_id: "chloe",
        tier: 2,
        name: "インナーピース",
        effect: SkillEffect::RecordOnly,
        note: "フォーカス使用中、MP持続減少量を半減",
    },
    MasteryDef {
        id: "chloe_m2_2",
        game_character_id: "chloe",
        tier: 2,
        name: "フォーカスオンターゲット",
        effect: SkillEffect::RecordOnly,
        note: "フォーカス使用中、最小命中率増加(+10%)",
    },
    MasteryDef {
        id: "chloe_m2_3",
        game_character_id: "chloe",
        tier: 2,
        name: "フロー",
        effect: SkillEffect::RecordOnly,
        note: "フォーカス使用中、MP持続減少量を2倍(最大MPの2%)に増やす代わりに基本追加ダメージが20%に増加",
    },
    MasteryDef {
        id: "chloe_m3_1",
        game_character_id: "chloe",
        tier: 3,
        name: "クイックウェザーリング",
        effect: SkillEffect::RecordOnly,
        note: "<風化の敵に&color(#000,#DFD){疾風系スキル};や&color(#000,#EED){大地系スキル};で攻撃時、<低速>デバフ付与（移動速度減少(-3)）",
    },
    MasteryDef {
        id: "chloe_m3_2",
        game_character_id: "chloe",
        tier: 3,
        name: "アイスフレーク",
        effect: SkillEffect::RecordOnly,
        note: "<氷化の敵に&color(#000,#DEF){水術系スキル};で攻撃時、追加ダメージ(10%)と<麻痺>付与 <氷化解除時、<麻痺>付与",
    },
    MasteryDef {
        id: "chloe_m3_3",
        game_character_id: "chloe",
        tier: 3,
        name: "アイアンリッチ",
        effect: SkillEffect::RecordOnly,
        note: "<雷電の敵に&color(#000,#DFF){雷術系スキル};で攻撃時、<感電／<石化>付与",
    },
    MasteryDef {
        id: "chloe_m4_1",
        game_character_id: "chloe",
        tier: 4,
        name: "ワイルドファイヤー",
        effect: SkillEffect::RecordOnly,
        note: "<炸裂の敵に&color(#000,#FDD){炎術系スキル};で攻撃すると、<ワイルドファイヤー>デバフ付与（被ダメージ増加(+10%)、持続時間2分）",
    },
    MasteryDef {
        id: "chloe_m4_2",
        game_character_id: "chloe",
        tier: 4,
        name: "クイックフリーズ",
        effect: SkillEffect::RecordOnly,
        note: "<氷化の敵に&color(#000,#DEF){水術系スキル};で攻撃すると、<クイックフリーズ>デバフ付与（最小命中率減少(-10%)／最小回避率減少(-10%)／移動速度減少(-3)、持続時間2分）",
    },
    MasteryDef {
        id: "chloe_m4_3",
        game_character_id: "chloe",
        tier: 4,
        name: "スパークリングアイス",
        effect: SkillEffect::RecordOnly,
        note: "<雷電の敵に&color(#000,#DFF){雷術系スキル};で攻撃すると、追加ダメージ(10%)",
    },
    MasteryDef {
        id: "chloe_m5_1",
        game_character_id: "chloe",
        tier: 5,
        name: "マナウォール - 防御型",
        effect: SkillEffect::RecordOnly,
        note: "マナウォール使用中、転換比率20%(カット率80%)",
    },
    MasteryDef {
        id: "chloe_m5_2",
        game_character_id: "chloe",
        tier: 5,
        name: "マナウォール - バランス",
        effect: SkillEffect::RecordOnly,
        note: "マナウォール使用中、転換比率30%(カット率70%)、攻撃ダメージ+5%",
    },
    MasteryDef {
        id: "chloe_m5_3",
        game_character_id: "chloe",
        tier: 5,
        name: "マナウォール - 攻撃型",
        effect: SkillEffect::RecordOnly,
        note: "マナウォール使用中、マナウォール防御なし、攻撃ダメージ+7%",
    },
    // --- isaac
    MasteryDef {
        id: "isaac_m1_1",
        game_character_id: "isaac",
        tier: 1,
        name: "コンカッション",
        effect: SkillEffect::RecordOnly,
        note: "[グロッキー]状態の敵は、持続してMPとSPが最大値の10%ずつ減少する。",
    },
    MasteryDef {
        id: "isaac_m1_2",
        game_character_id: "isaac",
        tier: 1,
        name: "モラバンド",
        effect: SkillEffect::RecordOnly,
        note: "[グロッキー]状態の敵は、持続的にダメージを受ける。(0.4s間隔) ※陣ではなく気絶に付随する状態異常ダメージ",
    },
    MasteryDef {
        id: "isaac_m1_3",
        game_character_id: "isaac",
        tier: 1,
        name: "アフターマス",
        effect: SkillEffect::RecordOnly,
        note: "[グロッキー]状態の敵は、最小回避率が減少する。(20%)",
    },
    MasteryDef {
        id: "isaac_m2_1",
        game_character_id: "isaac",
        tier: 2,
        name: "金剛不壞",
        effect: SkillEffect::RecordOnly,
        note: "[エネルギーフィールド]使用時、3秒間<無敵>となる。",
    },
    MasteryDef {
        id: "isaac_m2_2",
        game_character_id: "isaac",
        tier: 2,
        name: "プリチャージ",
        effect: SkillEffect::RecordOnly,
        note: "[エネルギーフィールド]の攻撃力が増加する。(50%)",
    },
    MasteryDef {
        id: "isaac_m2_3",
        game_character_id: "isaac",
        tier: 2,
        name: "アフターエフェクト",
        effect: SkillEffect::RecordOnly,
        note: "[エネルギーフィールド]のクールタイムが10秒増えるが、スキル終了後その場に引き寄せ効果のみ5秒持続。",
    },
    MasteryDef {
        id: "isaac_m3_1",
        game_character_id: "isaac",
        tier: 3,
        name: "ウィービング",
        effect: SkillEffect::RecordOnly,
        note: "[極・ウィービング] スキルを選択 最小回避率が増加する。SPを持続消費する。",
    },
    MasteryDef {
        id: "isaac_m3_2",
        game_character_id: "isaac",
        tier: 3,
        name: "ブロッキング",
        effect: SkillEffect::RecordOnly,
        note: "[極・ブロッキング] スキルを選択 高確率で被ダメージを軽減した上でSPで肩代わりする。",
    },
    MasteryDef {
        id: "isaac_m3_3",
        game_character_id: "isaac",
        tier: 3,
        name: "ショルダーロール",
        effect: SkillEffect::RecordOnly,
        note: "[極・ショルダーロール] スキルを選択 低確率で被ダメージを大きく軽減した上でSPで肩代わりする。",
    },
    MasteryDef {
        id: "isaac_m4_1",
        game_character_id: "isaac",
        tier: 4,
        name: "パワフルカウンター",
        effect: SkillEffect::RecordOnly,
        note: "[カウンターアタック]の攻撃力が増加する。(50%)",
    },
    MasteryDef {
        id: "isaac_m4_2",
        game_character_id: "isaac",
        tier: 4,
        name: "クロスカウンター",
        effect: SkillEffect::RecordOnly,
        note: "[カウンターアタック]が全ての状況に反撃する。その代わり、反撃するときもSPを消耗する。",
    },
    MasteryDef {
        id: "isaac_m4_3",
        game_character_id: "isaac",
        tier: 4,
        name: "フェイク",
        effect: SkillEffect::RecordOnly,
        note: "[カウンターアタック]で反撃するとき、50％の確率でダメージを与える代わりに、 被ダメージが増加+5%、最小回避率減少(-20%)効果を相手に与える。",
    },
    // --- isolet
    MasteryDef {
        id: "isolet_m1_1",
        game_character_id: "isolet",
        tier: 1,
        name: "神聖",
        effect: SkillEffect::RecordOnly,
        note: "攻撃時、対象に<神聖>デバフを付与する。 <神聖>デバフ：全属性減少(-10) [持続10s]",
    },
    MasteryDef {
        id: "isolet_m1_2",
        game_character_id: "isolet",
        tier: 1,
        name: "太陽の嵐",
        effect: SkillEffect::RecordOnly,
        note: "攻撃時、対象に<太陽の嵐>デバフを付与する。 <太陽の嵐>：対象に10秒間、1.2秒間隔で継続ダメージ(無属性,H依存,150%x2,Cri2.5x)",
    },
    MasteryDef {
        id: "isolet_m1_3",
        game_character_id: "isolet",
        tier: 1,
        name: "ヨズレル",
        effect: SkillEffect::Damage {
                category: DamageCategory::AttackDamageSkill,
                percent: 5.0,
            },
        note: "攻撃時、自身に<ヨズレル>バフを付与する。 <ヨズレル>：攻撃ダメージ増加(+10%) [持続20分]",
    },
    MasteryDef {
        id: "isolet_m2_1",
        game_character_id: "isolet",
        tier: 2,
        name: "ストームダンス",
        effect: SkillEffect::RecordOnly,
        note: "<ストームダンス> スキルを選択：[範囲攻撃]スキル 周辺の敵にスタン付与",
    },
    MasteryDef {
        id: "isolet_m2_2",
        game_character_id: "isolet",
        tier: 2,
        name: "ストームブレード",
        effect: SkillEffect::RecordOnly,
        note: "<ストームブレード> スキルを選択：[単体攻撃]スキル",
    },
    MasteryDef {
        id: "isolet_m2_3",
        game_character_id: "isolet",
        tier: 2,
        name: "ストームブラスト",
        effect: SkillEffect::RecordOnly,
        note: "<ストームブラスト> スキルを選択：[範囲攻撃]スキル ストームダンスよりクールタイム増加(+2s)／<月光の加護>消費増加(+5)、スキル倍率増加(+50%)、クリティカル(+0.5x)",
    },
    MasteryDef {
        id: "isolet_m3_1",
        game_character_id: "isolet",
        tier: 3,
        name: "光の歌（防御）",
        effect: SkillEffect::RecordOnly,
        note: "<光の歌>の追加効果 被ダメージ減少効果上昇(-10%)",
    },
    MasteryDef {
        id: "isolet_m3_2",
        game_character_id: "isolet",
        tier: 3,
        name: "光の歌（属性）",
        effect: SkillEffect::RecordOnly,
        note: "<光の歌>の追加効果 全属性増加効果上昇(+10)",
    },
    MasteryDef {
        id: "isolet_m3_3",
        game_character_id: "isolet",
        tier: 3,
        name: "光の歌（攻撃）",
        effect: SkillEffect::RecordOnly,
        note: "<光の歌>の追加効果 攻撃ダメージ増加効果上昇(+10%)",
    },
    // --- ispin
    MasteryDef {
        id: "ispin_m1_1",
        game_character_id: "ispin",
        tier: 1,
        name: "アンパッサン",
        effect: SkillEffect::RecordOnly,
        note: "[[[エンカレッジ]>#Increment]]追加効果、移動速度増加(+5)／後方からの攻撃時に与ダメージ増加(+10%)",
    },
    MasteryDef {
        id: "ispin_m1_2",
        game_character_id: "ispin",
        tier: 1,
        name: "キャッスリング",
        effect: SkillEffect::RecordOnly,
        note: "[[[エンカレッジ]>#Increment]]追加効果、被ダメージ減少(-10%)／装備の物理防御力増加(+10%) ※物理防御力補正が増加 プロテクトアーマーのような効果ではない",
    },
    MasteryDef {
        id: "ispin_m1_3",
        game_character_id: "ispin",
        tier: 1,
        name: "ヒートブレイド",
        effect: SkillEffect::RecordOnly,
        note: "[[[エンカレッジ]>#Increment]]追加効果、火属性増加(+10)",
    },
    MasteryDef {
        id: "ispin_m2_1",
        game_character_id: "ispin",
        tier: 2,
        name: "フルニール",
        effect: SkillEffect::RecordOnly,
        note: "[マーク・デ・ヴィクトワール]の動作を変更する。 効果領域が自身の周りを追従。領域内のメンバーは持続してHPを回復(1s毎に最大HPの10%)",
    },
    MasteryDef {
        id: "ispin_m2_2",
        game_character_id: "ispin",
        tier: 2,
        name: "コンケリール",
        effect: SkillEffect::RecordOnly,
        note: "[マーク・デ・ヴィクトワール]の動作を変更する。 敵対象に効果領域を付与。対象の被ダメージ増加(+10%)バフ付与",
    },
    MasteryDef {
        id: "ispin_m2_3",
        game_character_id: "ispin",
        tier: 2,
        name: "ス・バートル",
        effect: SkillEffect::RecordOnly,
        note: "[マーク・デ・ヴィクトワール]の動作を変更する。 特定地点に領域を設置。領域内の敵に持続ダメージ(100%/Cri2x)",
    },
    MasteryDef {
        id: "ispin_m3_1",
        game_character_id: "ispin",
        tier: 3,
        name: "トレーニングホイール",
        effect: SkillEffect::RecordOnly,
        note: "[鍛造]追加効果 <プシーキーの権能>デバフが掛った対象の攻撃ダメージ増加幅が減少する。",
    },
    MasteryDef {
        id: "ispin_m3_2",
        game_character_id: "ispin",
        tier: 3,
        name: "即刻的フィードバック",
        effect: SkillEffect::RecordOnly,
        note: "[鍛造]追加効果 <プシーキーの権能>デバフが掛った対象を倒すと、HP/SP/MPが回復する。",
    },
    MasteryDef {
        id: "ispin_m3_3",
        game_character_id: "ispin",
        tier: 3,
        name: "ハードトレーニング",
        effect: SkillEffect::RecordOnly,
        note: "[鍛造]追加効果 <鍛造>バフに攻撃ダメージ(+10%)の効果を付与",
    },
    MasteryDef {
        id: "ispin_m4_1",
        game_character_id: "ispin",
        tier: 4,
        name: "バックドラフト",
        effect: SkillEffect::RecordOnly,
        note: "<発火>デバフ追加効果、追加で同じダメージを与える。",
    },
    MasteryDef {
        id: "ispin_m4_2",
        game_character_id: "ispin",
        tier: 4,
        name: "パニック",
        effect: SkillEffect::RecordOnly,
        note: "<発火>デバフ追加効果、各ステータス値(-10%/2分)の<パニック>デバフ付与",
    },
    MasteryDef {
        id: "ispin_m4_3",
        game_character_id: "ispin",
        tier: 4,
        name: "サボタージュ",
        effect: SkillEffect::RecordOnly,
        note: "<発火>デバフ追加効果、装備能力値(-10%/2分)の<サボタージュ>デバフ付与",
    },
    // --- joshua
    MasteryDef {
        id: "joshua_m1_1",
        game_character_id: "joshua",
        tier: 1,
        name: "ハートフラッシュ",
        effect: SkillEffect::RecordOnly,
        note: "スペードシールドの効果をMP,SP回復量なし／HP回復量３倍へ変更",
    },
    MasteryDef {
        id: "joshua_m1_2",
        game_character_id: "joshua",
        tier: 1,
        name: "トラップカード",
        effect: SkillEffect::RecordOnly,
        note: "スペードシールド使用中、攻撃を受けると反撃する（100%,2x,一定確率(10%)で追加効果[感電])",
    },
    MasteryDef {
        id: "joshua_m1_3",
        game_character_id: "joshua",
        tier: 1,
        name: "エースイン・ザ・ホール",
        effect: SkillEffect::RecordOnly,
        note: "スペードシールド使用中、攻撃毎に追加ダメージ(10%)",
    },
    MasteryDef {
        id: "joshua_m2_1",
        game_character_id: "joshua",
        tier: 2,
        name: "オープンハンド",
        effect: SkillEffect::RecordOnly,
        note: "被ダメージ減少(-10%)",
    },
    MasteryDef {
        id: "joshua_m2_2",
        game_character_id: "joshua",
        tier: 2,
        name: "アノーイングネイバー",
        effect: SkillEffect::RecordOnly,
        note: "攻撃ダメージ増加(+10%)",
    },
    MasteryDef {
        id: "joshua_m2_3",
        game_character_id: "joshua",
        tier: 2,
        name: "エリート",
        effect: SkillEffect::RecordOnly,
        note: "憑依モード時のボーナス効果 剣闘士：STAB(+10%)、DEF(+10%) 魔法師：INT(+10%)、MR(+10%)",
    },
    MasteryDef {
        id: "joshua_m3_1",
        game_character_id: "joshua",
        tier: 3,
        name: "プレッシャー・オブ・ダクネス",
        effect: SkillEffect::RecordOnly,
        note: "アンプリフィケーションを使用すると、[マインドフューリー]バフがかかる。 攻撃時に[暗黒]／黒属性増加(+5)（持続時間 30分、チーム対象） [暗黒]状態の敵を攻撃すると追加ダメージ(10%)",
    },
    MasteryDef {
        id: "joshua_m3_2",
        game_character_id: "joshua",
        tier: 3,
        name: "プレッシャー・オブ・エレクトロ",
        effect: SkillEffect::RecordOnly,
        note: "アンプリフィケーションを使用すると、[マインドエレクトリック]バフがかかる。 攻撃時に[感電]／雷属性増加(+5)（持続時間 30分、チーム対象） [感電]状態の敵を攻撃すると追加ダメージ(10%)",
    },
    MasteryDef {
        id: "joshua_m3_3",
        game_character_id: "joshua",
        tier: 3,
        name: "プレッシャー・オブ・フロスト",
        effect: SkillEffect::RecordOnly,
        note: "アンプリフィケーションを使用すると、[マインドフリーズ]バフがかかる。 攻撃時に[霜]／水属性増加(+5)（持続時間 30分、チーム対象） [霜]状態の敵を攻撃すると追加ダメージ(10%)",
    },
    MasteryDef {
        id: "joshua_m4_1",
        game_character_id: "joshua",
        tier: 4,
        name: "レギュレート",
        effect: SkillEffect::RecordOnly,
        note: "ソウルバーストを使用時、被ダメージ減少(-5%)",
    },
    MasteryDef {
        id: "joshua_m4_2",
        game_character_id: "joshua",
        tier: 4,
        name: "ガーディアン",
        effect: SkillEffect::RecordOnly,
        note: "ソウルバースト使用中、被ダメージをMPに変換。 被ダメージ転換率(HP→MP)+100%／被ダメージ転換比率(HP→MP)+30%",
    },
    MasteryDef {
        id: "joshua_m4_3",
        game_character_id: "joshua",
        tier: 4,
        name: "エクソダス",
        effect: SkillEffect::RecordOnly,
        note: "ソウルバーストを使用時、攻撃ダメージ増加(+5%)",
    },
    // --- leeche
    MasteryDef {
        id: "leeche_m1_1",
        game_character_id: "leeche",
        tier: 1,
        name: "極・フォルテ",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m1_2",
        game_character_id: "leeche",
        tier: 1,
        name: "極・フォルティッシモ",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m1_3",
        game_character_id: "leeche",
        tier: 1,
        name: "極・メゾフォルテ",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m2_1",
        game_character_id: "leeche",
        tier: 2,
        name: "極・アレグロ",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m2_2",
        game_character_id: "leeche",
        tier: 2,
        name: "極・アレグロ・ディ・モルト",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m2_3",
        game_character_id: "leeche",
        tier: 2,
        name: "極・アレグレット",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m3_1",
        game_character_id: "leeche",
        tier: 3,
        name: "極・モリネト",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m3_2",
        game_character_id: "leeche",
        tier: 3,
        name: "極・モリネトポテンテ",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m3_3",
        game_character_id: "leeche",
        tier: 3,
        name: "極・モリネトアビーレ",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m4_1",
        game_character_id: "leeche",
        tier: 4,
        name: "極・保護の温もり",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m4_2",
        game_character_id: "leeche",
        tier: 4,
        name: "極・攻撃の熱気",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m4_3",
        game_character_id: "leeche",
        tier: 4,
        name: "極・強化された活力の剣",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m5_1",
        game_character_id: "leeche",
        tier: 5,
        name: "極・虚弱",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m5_2",
        game_character_id: "leeche",
        tier: 5,
        name: "極・手薄",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m5_3",
        game_character_id: "leeche",
        tier: 5,
        name: "極・悪意蓄積",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m6_1",
        game_character_id: "leeche",
        tier: 6,
        name: "極・爆気",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m6_2",
        game_character_id: "leeche",
        tier: 6,
        name: "極・酸化",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m6_3",
        game_character_id: "leeche",
        tier: 6,
        name: "極・薄弱",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m7_1",
        game_character_id: "leeche",
        tier: 7,
        name: "極・スピロ",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m7_2",
        game_character_id: "leeche",
        tier: 7,
        name: "極・リフィラーレ",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m7_3",
        game_character_id: "leeche",
        tier: 7,
        name: "極・アーゴグロッソ",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m8_1",
        game_character_id: "leeche",
        tier: 8,
        name: "極・圧殺",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m8_2",
        game_character_id: "leeche",
        tier: 8,
        name: "極・絞殺",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m8_3",
        game_character_id: "leeche",
        tier: 8,
        name: "極・悪気",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m9_1",
        game_character_id: "leeche",
        tier: 9,
        name: "極・クラヴァータ",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m9_2",
        game_character_id: "leeche",
        tier: 9,
        name: "極・テセーレ",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m9_3",
        game_character_id: "leeche",
        tier: 9,
        name: "極・クチーレ",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m10_1",
        game_character_id: "leeche",
        tier: 10,
        name: "極・ペンデュラム投擲",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m10_2",
        game_character_id: "leeche",
        tier: 10,
        name: "極・瞬間移動",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m10_3",
        game_character_id: "leeche",
        tier: 10,
        name: "極・回避起動",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m11_1",
        game_character_id: "leeche",
        tier: 11,
        name: "極・パラーレ",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m11_2",
        game_character_id: "leeche",
        tier: 11,
        name: "極・リスポスタ",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m11_3",
        game_character_id: "leeche",
        tier: 11,
        name: "極・コントラテンポ",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m12_1",
        game_character_id: "leeche",
        tier: 12,
        name: "極・勤勉な麦わら人形",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m12_2",
        game_character_id: "leeche",
        tier: 12,
        name: "極・危険な革の人形",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m12_3",
        game_character_id: "leeche",
        tier: 12,
        name: "極・優しいシルク人形",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m13_1",
        game_character_id: "leeche",
        tier: 13,
        name: "極・メリオ",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m13_2",
        game_character_id: "leeche",
        tier: 13,
        name: "極・ピウマジカ",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m13_3",
        game_character_id: "leeche",
        tier: 13,
        name: "極・ピウソリッド",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m14_1",
        game_character_id: "leeche",
        tier: 14,
        name: "極・治療",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m14_2",
        game_character_id: "leeche",
        tier: 14,
        name: "極・応急処置",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m14_3",
        game_character_id: "leeche",
        tier: 14,
        name: "極・心身高揚",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m15_1",
        game_character_id: "leeche",
        tier: 15,
        name: "極・アナローズの力",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m15_2",
        game_character_id: "leeche",
        tier: 15,
        name: "極・アナローズの活力",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    MasteryDef {
        id: "leeche_m15_3",
        game_character_id: "leeche",
        tier: 15,
        name: "極・アナローズの犠牲",
        effect: SkillEffect::RecordOnly,
        note: "スキルの選択(解説は wiki のスキル本体)",
    },
    // --- lucian
    MasteryDef {
        id: "lucian_m1_1",
        game_character_id: "lucian",
        tier: 1,
        name: "刃風",
        effect: SkillEffect::RecordOnly,
        note: "攻撃成功時に、対象に10秒間、1秒間隔で継続ダメージ(150%x2,Cri2.5x)",
    },
    MasteryDef {
        id: "lucian_m1_2",
        game_character_id: "lucian",
        tier: 1,
        name: "旋風",
        effect: SkillEffect::RecordOnly,
        note: "攻撃成功時に、対象に10秒間、命中率減少(-10%)／移動速度減少(-3)",
    },
    MasteryDef {
        id: "lucian_m1_3",
        game_character_id: "lucian",
        tier: 1,
        name: "そよ風",
        effect: SkillEffect::RecordOnly,
        note: "攻撃成功時に、対象に10秒間、最小回避率減少(-10%)／被ダメージ増加+5%",
    },
    MasteryDef {
        id: "lucian_m2_1",
        game_character_id: "lucian",
        tier: 2,
        name: "神速剣",
        effect: SkillEffect::RecordOnly,
        note: "<ラグランジュ神速剣>の効果変更 前後ディレイ(-75%)、後ディレイ追加(-45%) ※簡易計算値：ディレイ減少(前75%/後86%)",
    },
    MasteryDef {
        id: "lucian_m2_2",
        game_character_id: "lucian",
        tier: 2,
        name: "強剣",
        effect: SkillEffect::RecordOnly,
        note: "<ラグランジュ神速剣>の効果変更 前後ディレイ(+50%)、後ディレイ追加(+30%)、与ダメージ増加(+10%) ※簡易計算値：ディレイ増加(前50%/後65%)",
    },
    MasteryDef {
        id: "lucian_m2_3",
        game_character_id: "lucian",
        tier: 2,
        name: "幻剣",
        effect: SkillEffect::RecordOnly,
        note: "<ラグランジュ神速剣>に効果追加 前後ディレイ(-50%)、後ディレイ追加(-30%)、攻撃成功時に<スタン>5s/<スロー>10s ※簡易計算値：ディレイ減少(前50%/後65%)",
    },
    MasteryDef {
        id: "lucian_m3_1",
        game_character_id: "lucian",
        tier: 3,
        name: "強固な意志の連撃",
        effect: SkillEffect::RecordOnly,
        note: "<連撃>、<無双乱舞>、<旋風斬>の効果追加 被ダメージ減少(-5%)",
    },
    MasteryDef {
        id: "lucian_m3_2",
        game_character_id: "lucian",
        tier: 3,
        name: "絶え間ない連撃",
        effect: SkillEffect::RecordOnly,
        note: "<連撃>、<無双乱舞>、<旋風斬>の効果追加 持続時間延長(+5s)／クールタイム増加(+3s)／最小命中率増加(+3%)／攻撃対象の全能力値減少(-5%)",
    },
    MasteryDef {
        id: "lucian_m3_3",
        game_character_id: "lucian",
        tier: 3,
        name: "力を込めた連撃",
        effect: SkillEffect::RecordOnly,
        note: "<連撃>、<無双乱舞>、<旋風斬>の効果追加 与ダメージ増加(+5%)",
    },
    MasteryDef {
        id: "lucian_m4_1",
        game_character_id: "lucian",
        tier: 4,
        name: "誘引",
        effect: SkillEffect::RecordOnly,
        note: "<鉄壁>の効果追加 ※[エンクルム]と同時使用不可 効果範囲内のチームメンバーの被ダメージの一部をルシアンが引き受ける ダメージ転移[%]＝50 - [素DEF]÷30 + [風属性]÷20 (最小5%)",
    },
    MasteryDef {
        id: "lucian_m4_2",
        game_character_id: "lucian",
        tier: 4,
        name: "スタボーン",
        effect: SkillEffect::RecordOnly,
        note: "<鉄壁>の効果追加 効果範囲内のチームメンバーの最小命中率増加(+10%)／敵の全能力値減少(-10%)",
    },
    MasteryDef {
        id: "lucian_m4_3",
        game_character_id: "lucian",
        tier: 4,
        name: "集中攻撃",
        effect: SkillEffect::RecordOnly,
        note: "<鉄壁>の効果追加 効果範囲内のチームメンバーが敵を攻撃するとき、一定確率で追加ダメージ(10%)",
    },
    // --- maximin
    MasteryDef {
        id: "maximin_m1_1",
        game_character_id: "maximin",
        tier: 1,
        name: "把握",
        effect: SkillEffect::RecordOnly,
        note: "悪い状態異常の持続時間減少(-20%)。 ※スキルやアイテムで解除不可／持続時間固定の場合は減らない。",
    },
    MasteryDef {
        id: "maximin_m1_2",
        game_character_id: "maximin",
        tier: 1,
        name: "状況判断",
        effect: SkillEffect::RecordOnly,
        note: "自分と周囲のチームメンバーの移動速度増加(+5)",
    },
    MasteryDef {
        id: "maximin_m1_3",
        game_character_id: "maximin",
        tier: 1,
        name: "怠惰",
        effect: SkillEffect::Damage {
                category: DamageCategory::AttackDamageSkill,
                percent: 3.0,
            },
        note: "攻撃ダメージが増加する。(+3%)",
    },
    MasteryDef {
        id: "maximin_m2_1",
        game_character_id: "maximin",
        tier: 2,
        name: "侮辱",
        effect: SkillEffect::RecordOnly,
        note: "<毒舌>に能力値減少(-10%)を追加",
    },
    MasteryDef {
        id: "maximin_m2_2",
        game_character_id: "maximin",
        tier: 2,
        name: "皮肉",
        effect: SkillEffect::RecordOnly,
        note: "<毒舌>に最小命中率減少(-10%)を追加",
    },
    MasteryDef {
        id: "maximin_m2_3",
        game_character_id: "maximin",
        tier: 2,
        name: "暴言",
        effect: SkillEffect::RecordOnly,
        note: "<毒舌>に最終ダメージ-10%を追加",
    },
    MasteryDef {
        id: "maximin_m3_1",
        game_character_id: "maximin",
        tier: 3,
        name: "呪われた魔剣",
        effect: SkillEffect::RecordOnly,
        note: "<呪われた魔剣>の効果：攻撃ダメージ/被ダメージ増加(+5%)、持続時間20s、CT1分",
    },
    MasteryDef {
        id: "maximin_m3_2",
        game_character_id: "maximin",
        tier: 3,
        name: "封印された魔剣",
        effect: SkillEffect::RecordOnly,
        note: "<呪われた魔剣>の効果：攻撃ダメージ増加(+5%)、持続時間2分、CT10分",
    },
    MasteryDef {
        id: "maximin_m3_3",
        game_character_id: "maximin",
        tier: 3,
        name: "自我を持つ魔剣",
        effect: SkillEffect::RecordOnly,
        note: "<呪われた魔剣>の効果：攻撃ダメージ/被ダメージ増加(+7%)、持続時間2分、CT10分",
    },
    MasteryDef {
        id: "maximin_m4_1",
        game_character_id: "maximin",
        tier: 4,
        name: "剣を扱う技術",
        effect: SkillEffect::StatRate {
            stats: HACK_DEF,
            percent: 10.0,
            layer: StatLayer::MultiplierB,
        },
        note: "HACK+10%、DEF+10%",
    },
    MasteryDef {
        id: "maximin_m4_2",
        game_character_id: "maximin",
        tier: 4,
        name: "風使い",
        effect: SkillEffect::RecordOnly,
        note: "攻撃時、一定確率で<スタン>付与",
    },
    MasteryDef {
        id: "maximin_m4_3",
        game_character_id: "maximin",
        tier: 4,
        name: "棒のように振るう剣",
        effect: SkillEffect::RecordOnly,
        note: "攻撃スキルを使用する際、対象の物理防御力と魔法防御力が一定量低下(-7%)したものとみなしてダメージを与える",
    },
    // --- mira
    MasteryDef {
        id: "mira_m1_1",
        game_character_id: "mira",
        tier: 1,
        name: "セルフコントロール",
        effect: SkillEffect::RecordOnly,
        note: "[銭投げ]、[紅い射手の砲撃]、[ラッキーダイス]の消費SEED-50%。 マスタリー変更時に付与済みの[ラッキーダイス]は解除されるので注意。",
    },
    MasteryDef {
        id: "mira_m1_2",
        game_character_id: "mira",
        tier: 1,
        name: "アンティ",
        effect: SkillEffect::RecordOnly,
        note: "[銭投げ]、[紅い射手の砲撃]、[ラッキーダイス]の消費SEED+100%になるが、 [銭投げ]、[紅い射手の砲撃]の攻撃力が増加し、[ラッキーダイス]のサイコロが1が出てくる確率が減る。 マスタリー変更時に付与済みの[ラッキーダイス]は解除されるので注意。",
    },
    MasteryDef {
        id: "mira_m1_3",
        game_character_id: "mira",
        tier: 1,
        name: "ポーカーフェイス",
        effect: SkillEffect::RecordOnly,
        note: "[ラッキーダイス]のサイコロの出目が1になる確率と6になる確率がそれぞれ20％増加する。 マスタリー変更時に付与済みの[ラッキーダイス]は解除されるので注意。",
    },
    MasteryDef {
        id: "mira_m2_1",
        game_character_id: "mira",
        tier: 2,
        name: "スプリング",
        effect: SkillEffect::RecordOnly,
        note: "[ハイジャンプ]のクールタイムが消え、射程距離が増える。",
    },
    MasteryDef {
        id: "mira_m2_2",
        game_character_id: "mira",
        tier: 2,
        name: "バインドヴァイパー",
        effect: SkillEffect::RecordOnly,
        note: "[ハイジャンプ]を使用すると、着地点の周辺にいる敵を引き寄せる。",
    },
    MasteryDef {
        id: "mira_m2_3",
        game_character_id: "mira",
        tier: 2,
        name: "ヴァイパーズアイ",
        effect: SkillEffect::RecordOnly,
        note: "[ハイジャンプ]を使用すると、一定時間、後方攻撃時の与ダメージが増加(+20%, 5分)",
    },
    MasteryDef {
        id: "mira_m3_1",
        game_character_id: "mira",
        tier: 3,
        name: "エスケープ",
        effect: SkillEffect::RecordOnly,
        note: "[ダガーストーム]のクールタイムが消え、効果範囲が増加し、より遠くへ後退する。",
    },
    MasteryDef {
        id: "mira_m3_2",
        game_character_id: "mira",
        tier: 3,
        name: "ゲットオーバー",
        effect: SkillEffect::RecordOnly,
        note: "[ダガーストーム]を使用すると、追加ダメージを与える。追加ダメージはミラのHPが0に近いほど上昇する。",
    },
    MasteryDef {
        id: "mira_m3_3",
        game_character_id: "mira",
        tier: 3,
        name: "ベノムティス",
        effect: SkillEffect::RecordOnly,
        note: "[ダガーストーム]を使用すると、[中毒]と[麻痺]を引き起こす。",
    },
    MasteryDef {
        id: "mira_m4_1",
        game_character_id: "mira",
        tier: 4,
        name: "アドレナリン",
        effect: SkillEffect::RecordOnly,
        note: "[スパート]使用中、後ディレイが100％減少する。",
    },
    MasteryDef {
        id: "mira_m4_2",
        game_character_id: "mira",
        tier: 4,
        name: "グッドフェイス",
        effect: SkillEffect::RecordOnly,
        note: "[スパート]の移動速度増加の効果が消える代わりに、持続時間が増加する。使用中、中ディレイ低下率固定(5%)",
    },
    MasteryDef {
        id: "mira_m4_3",
        game_character_id: "mira",
        tier: 4,
        name: "リズミカル",
        effect: SkillEffect::RecordOnly,
        note: "[スパート]使用中、[後ディレイ固定]となる。",
    },
    // --- nayatorei
    MasteryDef {
        id: "nayatorei_m1_1",
        game_character_id: "nayatorei",
        tier: 1,
        name: "強奪",
        effect: SkillEffect::RecordOnly,
        note: "[閃]の攻撃対象に<強奪>デバフ：全ステータス値(-10%)/装備攻撃力(-10%) (持続時間:2分)",
    },
    MasteryDef {
        id: "nayatorei_m1_2",
        game_character_id: "nayatorei",
        tier: 1,
        name: "筋斬り",
        effect: SkillEffect::RecordOnly,
        note: "[閃]の攻撃対象に<絶筋>デバフ：全ステータス値(-10%)/最小回避率(-10%)/最小命中率(-10%)/移動速度(-3) (持続時間:2分)",
    },
    MasteryDef {
        id: "nayatorei_m1_3",
        game_character_id: "nayatorei",
        tier: 1,
        name: "爆弾付着",
        effect: SkillEffect::RecordOnly,
        note: "[閃]の攻撃対象に2秒後に追加ダメージ (190x2/Cri2.5x)",
    },
    MasteryDef {
        id: "nayatorei_m2_1",
        game_character_id: "nayatorei",
        tier: 2,
        name: "身隠しの煙幕",
        effect: SkillEffect::RecordOnly,
        note: "[煙幕]を使用すると、敵にターゲットされない<未隠れ>バフが付与される。攻撃すれと即時切れるが、霧の中に入ればバフは更新される。（持続時間 5s）",
    },
    MasteryDef {
        id: "nayatorei_m2_2",
        game_character_id: "nayatorei",
        tier: 2,
        name: "敵を欺く煙幕",
        effect: SkillEffect::RecordOnly,
        note: "[煙幕]を使用すると、<強襲>が付与される。 <強襲>バフは、攻撃時に一度だけ追加ダメージ(+50%)を与える（持続時間 30s）",
    },
    MasteryDef {
        id: "nayatorei_m2_3",
        game_character_id: "nayatorei",
        tier: 2,
        name: "毒入り煙幕",
        effect: SkillEffect::RecordOnly,
        note: "[煙幕]上にいる対象は、1.5s毎に<中毒+1>付与される。",
    },
    MasteryDef {
        id: "nayatorei_m3_1",
        game_character_id: "nayatorei",
        tier: 3,
        name: "後ろを狙う襲撃",
        effect: SkillEffect::RecordOnly,
        note: "[襲撃]で対象の後方から攻撃すると追加ダメージ(+50%)を与える。",
    },
    MasteryDef {
        id: "nayatorei_m3_2",
        game_character_id: "nayatorei",
        tier: 3,
        name: "体重を乗せた襲撃",
        effect: SkillEffect::RecordOnly,
        note: "[襲撃]で対象を攻撃すると追加ダメージ（距離20以上で50%、距離10以上で35%、距離0以上で20%）を与える。",
    },
    MasteryDef {
        id: "nayatorei_m3_3",
        game_character_id: "nayatorei",
        tier: 3,
        name: "無差別的な襲撃",
        effect: SkillEffect::RecordOnly,
        note: "[襲撃](チャージ・スプレッド)を[無差別的な襲撃](前ディレイなし範囲)に変更する。",
    },
    MasteryDef {
        id: "nayatorei_m4_1",
        game_character_id: "nayatorei",
        tier: 4,
        name: "毒塗り",
        effect: SkillEffect::RecordOnly,
        note: "<連>、<花蝶乱舞>、<心>、<手裏剣投げ>、<狂猫>、<分身乱撃>、<忍術 閃>、<襲撃>、<無差別的な襲撃>で敵を攻撃すると<中毒>がかかる。",
    },
    MasteryDef {
        id: "nayatorei_m4_2",
        game_character_id: "nayatorei",
        tier: 4,
        name: "致命的な毒",
        effect: SkillEffect::RecordOnly,
        note: "<中毒>状態の対象を攻撃すると、スタック量に応じた中毒ダメージを与える。クールタイム1.2s。",
    },
    MasteryDef {
        id: "nayatorei_m4_3",
        game_character_id: "nayatorei",
        tier: 4,
        name: "無気力になる毒",
        effect: SkillEffect::RecordOnly,
        note: "<中毒>状態の対象を攻撃すると、攻撃ダメージ減少(-10%)のデバフを付与する",
    },
    // --- nocturne
    MasteryDef {
        id: "nocturne_m1_1",
        game_character_id: "nocturne",
        tier: 1,
        name: "クイックチャージ",
        effect: SkillEffect::RecordOnly,
        note: "<レーザーカノン>/<プラズマカノン> チャージ速度短縮(0.3s)、攻撃ダメージ減少(-20%)",
    },
    MasteryDef {
        id: "nocturne_m1_2",
        game_character_id: "nocturne",
        tier: 1,
        name: "チャージバースト",
        effect: SkillEffect::RecordOnly,
        note: "<レーザーカノン>/<プラズマカノン> チャージ速度延長(1.1s)、攻撃ダメージ増加(+100%)",
    },
    MasteryDef {
        id: "nocturne_m1_3",
        game_character_id: "nocturne",
        tier: 1,
        name: "インデュアチャージ",
        effect: SkillEffect::RecordOnly,
        note: "<レーザーカノン>/<プラズマカノン> チャージ速度基本(1.0s)、対象に被ダメージ増加(+10%/2分)デバフを追加で付与",
    },
    MasteryDef {
        id: "nocturne_m2_1",
        game_character_id: "nocturne",
        tier: 2,
        name: "サンダーボルト",
        effect: SkillEffect::RecordOnly,
        note: "<感電>状態の敵に攻撃成功時、対象に10%の確率でスタンを付与",
    },
    MasteryDef {
        id: "nocturne_m2_2",
        game_character_id: "nocturne",
        tier: 2,
        name: "エレクトリックショック",
        effect: SkillEffect::RecordOnly,
        note: "<感電>状態の敵に攻撃成功時、対象に攻撃ダメージ減少(10%)",
    },
    MasteryDef {
        id: "nocturne_m2_3",
        game_character_id: "nocturne",
        tier: 2,
        name: "ライトニングアタック",
        effect: SkillEffect::RecordOnly,
        note: "<感電>状態の敵に攻撃成功時、対象に与えたダメージの10%の追加ダメージ",
    },
    MasteryDef {
        id: "nocturne_m3_1",
        game_character_id: "nocturne",
        tier: 3,
        name: "サテライトカノン",
        effect: SkillEffect::RecordOnly,
        note: "<サテライトカノン> スキルを選択",
    },
    MasteryDef {
        id: "nocturne_m3_2",
        game_character_id: "nocturne",
        tier: 3,
        name: "クラスターロケット",
        effect: SkillEffect::RecordOnly,
        note: "<クラスターロケット> スキルを選択",
    },
    MasteryDef {
        id: "nocturne_m3_3",
        game_character_id: "nocturne",
        tier: 3,
        name: "クアンタムニュークリア",
        effect: SkillEffect::RecordOnly,
        note: "<クアンタムニュークリア> スキルを選択",
    },
    // --- ranjie
    MasteryDef {
        id: "ranjie_m1_1",
        game_character_id: "ranjie",
        tier: 1,
        name: "散弾リボルバー",
        effect: SkillEffect::RecordOnly,
        note: "[極・散弾リボルバー] スキルを選択 ６回攻撃後にCT60秒、１回でも発動すると６回攻撃しなくとも一定時間後にCTが発生する",
    },
    MasteryDef {
        id: "ranjie_m1_2",
        game_character_id: "ranjie",
        tier: 1,
        name: "トリプルリボルバー",
        effect: SkillEffect::RecordOnly,
        note: "[極・トリプルリボルバー] スキルを選択 ６回攻撃後にCT60秒、１回でも発動すると６回攻撃しなくとも一定時間後にCTが発生する",
    },
    MasteryDef {
        id: "ranjie_m1_3",
        game_character_id: "ranjie",
        tier: 1,
        name: "フラッシュバン",
        effect: SkillEffect::RecordOnly,
        note: "[極・フラッシュバン] スキルを選択 対象に些細なダメージと[暗黒]デバフを付与する",
    },
    MasteryDef {
        id: "ranjie_m2_1",
        game_character_id: "ranjie",
        tier: 2,
        name: "マズルブレーキ",
        effect: SkillEffect::RecordOnly,
        note: "装備の命中率が10%増加、クリティカル確率が増加",
    },
    MasteryDef {
        id: "ranjie_m2_2",
        game_character_id: "ranjie",
        tier: 2,
        name: "サイレンサー",
        effect: SkillEffect::Damage {
                category: DamageCategory::AttackDamageSkill,
                percent: 3.0,
            },
        note: "攻撃ダメージ増加3% モンスターにターゲットされにくくなる",
    },
    MasteryDef {
        id: "ranjie_m2_3",
        game_character_id: "ranjie",
        tier: 2,
        name: "ロングバレル",
        effect: SkillEffect::RecordOnly,
        note: "銃スキルの射程距離がわずかに増加",
    },
    MasteryDef {
        id: "ranjie_m3_1",
        game_character_id: "ranjie",
        tier: 3,
        name: "拡張弾",
        effect: SkillEffect::RecordOnly,
        note: "弾攻撃スキル使用時、[出血]（継続ダメージ）と[低速]デバフ付与",
    },
    MasteryDef {
        id: "ranjie_m3_2",
        game_character_id: "ranjie",
        tier: 3,
        name: "貫通弾",
        effect: SkillEffect::RecordOnly,
        note: "装備の命中率(セット効果は対象外)が10%減少、射程距離が4減少 自身の与ダメージ計算時に敵の防御値（物防&魔防）が減少(-15%)したとして計算する（※デバフではないので他ＰＣに影響しない）",
    },
    MasteryDef {
        id: "ranjie_m3_3",
        game_character_id: "ranjie",
        tier: 3,
        name: "麻酔弾",
        effect: SkillEffect::RecordOnly,
        note: "敵に与ダメージ減少(-5%)効果付与（[麻酔弾]デバフ） [麻酔弾]が5回ネストされたら、[麻痺]デバフ付与",
    },
    MasteryDef {
        id: "ranjie_m4_1",
        game_character_id: "ranjie",
        tier: 4,
        name: "アイスソード",
        effect: SkillEffect::RecordOnly,
        note: "[極・アイスソード] スキルを選択 アイスソードを設置、装置の近くにいる敵に攻撃すると追加ダメージを与える。 装置が破壊されると爆発して、周囲に[霜]デバフをばらまく",
    },
    MasteryDef {
        id: "ranjie_m4_2",
        game_character_id: "ranjie",
        tier: 4,
        name: "アップライジング",
        effect: SkillEffect::RecordOnly,
        note: "[極・アップライジング] スキルを選択 ガス範囲内にいる間だけ敵味方へ[極・アップライジング]バフ（攻撃/被ダメージ10%増加）を付与 [極・撹乱]と重複可",
    },
    MasteryDef {
        id: "ranjie_m4_3",
        game_character_id: "ranjie",
        tier: 4,
        name: "ララバイ",
        effect: SkillEffect::RecordOnly,
        note: "[極・ララバイ] スキルを選択 ガス内の敵は[極・ララバイ]（命中率減少、最小回避率減少）／[睡眠]が付与され、持続的にMP減少（持続時間 30s）",
    },
    // --- roamini
    MasteryDef {
        id: "roamini_m1_1",
        game_character_id: "roamini",
        tier: 1,
        name: "シンボルオブステディ",
        effect: SkillEffect::RecordOnly,
        note: "カース・ペンジュラム、ベノムノヴァの持続時間が2倍に増加する。",
    },
    MasteryDef {
        id: "roamini_m1_2",
        game_character_id: "roamini",
        tier: 1,
        name: "シンボルオブフラッシュ",
        effect: SkillEffect::RecordOnly,
        note: "カース・ペンジュラム、ベノムノヴァの持続時間とクールタイムが半減する。",
    },
    MasteryDef {
        id: "roamini_m1_3",
        game_character_id: "roamini",
        tier: 1,
        name: "シンボルオブスピリット",
        effect: SkillEffect::RecordOnly,
        note: "カース・ペンジュラム、ベノムノヴァの効果を強化、クールタイムが1.5倍に増加する。 カース・ペンジュラム：被ダメージ増加(+5%)、敵の与ダメージ減少(-5%)、 全能力値減少(-5%)、チームメンバーの与ダメージ増加(+5%) ベノムノヴァ：ダメージ増加(約1.5倍)、中毒数増加(+4)",
    },
    MasteryDef {
        id: "roamini_m2_1",
        game_character_id: "roamini",
        tier: 2,
        name: "逼迫",
        effect: SkillEffect::RecordOnly,
        note: "カース・エンドのクールタイム短縮(5s→3s)",
    },
    MasteryDef {
        id: "roamini_m2_2",
        game_character_id: "roamini",
        tier: 2,
        name: "良心",
        effect: SkillEffect::RecordOnly,
        note: "カース・エンドの与ダメージが1.5倍になる",
    },
    MasteryDef {
        id: "roamini_m2_3",
        game_character_id: "roamini",
        tier: 2,
        name: "怨恨",
        effect: SkillEffect::RecordOnly,
        note: "範囲スキルカース・エンドを単体スキル怨恨に変更する。",
    },
    MasteryDef {
        id: "roamini_m3_1",
        game_character_id: "roamini",
        tier: 3,
        name: "バフラーム",
        effect: SkillEffect::RecordOnly,
        note: "[[[バフラーム]>#Mastary4_1]] スキルを選択 最小回避率とAGI(+10%)、移動速度(+5)が増加する。",
    },
    MasteryDef {
        id: "roamini_m3_2",
        game_character_id: "roamini",
        tier: 3,
        name: "パウアトゥン",
        effect: SkillEffect::RecordOnly,
        note: "[[[パウアトゥン]>#Mastary4_2]] スキルを選択 被ダメージ減少(-10%)、DEF/MR/最大HPが増加(+10%)",
    },
    MasteryDef {
        id: "roamini_m3_3",
        game_character_id: "roamini",
        tier: 3,
        name: "ア・プチ",
        effect: SkillEffect::RecordOnly,
        note: "[[[ア・プチ]>#Mastary4_3]] スキルを選択 与ダメージ増加(+10%)、INT増加(+10%)、スキルの射程距離(+4)",
    },
    // --- siberin
    MasteryDef {
        id: "siberin_m1_1",
        game_character_id: "siberin",
        tier: 1,
        name: "欺瞞",
        effect: SkillEffect::RecordOnly,
        note: "<挑発に最小回避率減少(-10%)を追加",
    },
    MasteryDef {
        id: "siberin_m1_2",
        game_character_id: "siberin",
        tier: 1,
        name: "軽蔑",
        effect: SkillEffect::RecordOnly,
        note: "<挑発に最小命中率減少(-10%)を追加",
    },
    MasteryDef {
        id: "siberin_m1_3",
        game_character_id: "siberin",
        tier: 1,
        name: "嘲笑",
        effect: SkillEffect::RecordOnly,
        note: "<挑発の与ダメージ増加を削除（対象の被ダメージ増加のみとなり、デメリットがなくなる）",
    },
    MasteryDef {
        id: "siberin_m2_1",
        game_character_id: "siberin",
        tier: 2,
        name: "槍術",
        effect: SkillEffect::Damage {
                category: DamageCategory::AttackDamageSkill,
                percent: 5.0,
            },
        note: "攻撃ダメージ増加する(+10%)",
    },
    MasteryDef {
        id: "siberin_m2_2",
        game_character_id: "siberin",
        tier: 2,
        name: "棒術",
        effect: SkillEffect::RecordOnly,
        note: "攻撃スキルを使用する際、対象の物理防御力と魔法防御力が一定量低下(-7%)したものとみなしてダメージを与える",
    },
    MasteryDef {
        id: "siberin_m2_3",
        game_character_id: "siberin",
        tier: 2,
        name: "地稽古",
        effect: SkillEffect::RecordOnly,
        note: "被ダメージが減少する(-5%)",
    },
    MasteryDef {
        id: "siberin_m3_1",
        game_character_id: "siberin",
        tier: 3,
        name: "業火",
        effect: SkillEffect::RecordOnly,
        note: "<発火デバフ追加効果、追加で同じダメージを与える。",
    },
    MasteryDef {
        id: "siberin_m3_2",
        game_character_id: "siberin",
        tier: 3,
        name: "コーマ",
        effect: SkillEffect::RecordOnly,
        note: "<発火デバフ追加効果、各ステータス値(-10%/2分)の<パニック>デバフ付与 ※イスピン・マスタリー[[[パニック]>Skill/イスピン#MasteryList]]と併用不可",
    },
    MasteryDef {
        id: "siberin_m3_3",
        game_character_id: "siberin",
        tier: 3,
        name: "フィアー",
        effect: SkillEffect::RecordOnly,
        note: "<発火デバフ追加効果、装備能力値(-10%/2分)の<サボタージュ>デバフ付与 ※イスピン・マスタリー[[[サボタージュ]>Skill/イスピン#MasteryList]]と併用不可",
    },
    MasteryDef {
        id: "siberin_m4_1",
        game_character_id: "siberin",
        tier: 4,
        name: "バーサーカー",
        effect: SkillEffect::RecordOnly,
        note: "攻撃成功時に10％の確率でHP回復（回復量＝[攻撃ダメージ]×0.03、最大HPの5%まで回復）",
    },
    MasteryDef {
        id: "siberin_m4_2",
        game_character_id: "siberin",
        tier: 4,
        name: "不屈",
        effect: SkillEffect::Damage {
                category: DamageCategory::AttackDamageSkill,
                percent: 5.0,
            },
        note: "被ダメージ毎に<不屈>バフ<+1>（最大スタック数:10）※攻撃ダメージ／被ダメージ増加：＋スタック数[%] ※マスタリー選択/解除、毎日0時に増加値はリセット",
    },
    MasteryDef {
        id: "siberin_m4_3",
        game_character_id: "siberin",
        tier: 4,
        name: "暴走",
        effect: SkillEffect::Damage {
                category: DamageCategory::AttackDamageSkill,
                percent: 20.0,
            },
        note: "マスタリー選択後の累積ダメージが[最大HP]の5倍以上であれば、60秒間、攻撃ダメージ+60％ 毎秒最大HPの10％、HP減少再使用制限60s ※マスタリー選択/解除、毎日0時に増加値はリセット",
    },
    MasteryDef {
        id: "siberin_m5_1",
        game_character_id: "siberin",
        tier: 5,
        name: "バーサーク-攻撃型",
        effect: SkillEffect::RecordOnly,
        note: "<バーサーク>の効果を変更する。攻撃力が大幅に増加し、防御力とディレイが大幅に減少する。 攻撃ダメージ+30%/被ダメージ+20%/移動速度+3/前ディレイ-20%/後ディレイ-20%/硬直無視",
    },
    MasteryDef {
        id: "siberin_m5_2",
        game_character_id: "siberin",
        tier: 5,
        name: "バーサーク-バランス型",
        effect: SkillEffect::RecordOnly,
        note: "<バーサーク>の効果を変更する。攻撃力が小幅に増加し、防御力とディレイが小幅に減少する。 攻撃ダメージ+20%/被ダメージ+10%/移動速度+3/前ディレイ-10%/後ディレイ-10%/硬直無視",
    },
    MasteryDef {
        id: "siberin_m5_3",
        game_character_id: "siberin",
        tier: 5,
        name: "バーサーク-防御型",
        effect: SkillEffect::RecordOnly,
        note: "<バーサーク>の効果を変更する。攻撃力は増加しないが、防御力が増加する。 被ダメージ-10%/移動速度+3/硬直無視",
    },
    // --- tichiel
    MasteryDef {
        id: "tichiel_m1_1",
        game_character_id: "tichiel",
        tier: 1,
        name: "怪我したとき！",
        effect: SkillEffect::RecordOnly,
        note: "[極・怪我したとき！] スキルを選択 自身を含む、周辺のチームメイトのHPを持続して回復（※持続時間 5分、2秒毎 HP15%、最大回復量HP5000）",
    },
    MasteryDef {
        id: "tichiel_m1_2",
        game_character_id: "tichiel",
        tier: 1,
        name: "つらいとき！",
        effect: SkillEffect::RecordOnly,
        note: "[極・つらいとき！] スキルを選択 自身を含む、周辺のチームメイトのHPとSPを持続して回復（※持続時間 5分、2秒毎 HP7%/SP21%、最大回復量HP2500/SP1200）",
    },
    MasteryDef {
        id: "tichiel_m1_3",
        game_character_id: "tichiel",
        tier: 1,
        name: "ブルーなとき！",
        effect: SkillEffect::RecordOnly,
        note: "[極・ブルーなとき！] スキルを選択 自身を含む、周辺のチームメイトのHPとMPを持続して回復（※持続時間 5分、2秒毎 HP7%/MP14%、最大回復量HP2500/MP999）",
    },
    MasteryDef {
        id: "tichiel_m2_1",
        game_character_id: "tichiel",
        tier: 2,
        name: "レモンジャム除去剤",
        effect: SkillEffect::RecordOnly,
        note: "[極・レモンジャム除去剤] スキルを選択 範囲内のチームメイトは持続的に状態異常が解除され、敵はダメージを受ける（持続時間 60秒）",
    },
    MasteryDef {
        id: "tichiel_m2_2",
        game_character_id: "tichiel",
        tier: 2,
        name: "変な三色カクテル",
        effect: SkillEffect::RecordOnly,
        note: "[極・変な三色カクテル] スキルを選択 範囲内の対象は、移動速度(-2)／最小回避率(-20%)／最小命中率(-20%)／クリティカル確率(-20%)が減少（持続時間 2分）",
    },
    MasteryDef {
        id: "tichiel_m2_3",
        game_character_id: "tichiel",
        tier: 2,
        name: "失敗したエリクサー",
        effect: SkillEffect::RecordOnly,
        note: "[極・失敗したエリクサー] スキルを選択 範囲内の対象は、HP回復量(-50%)／悪い状態異常にかかる確率(+75%)（持続時間 2分）",
    },
    MasteryDef {
        id: "tichiel_m3_1",
        game_character_id: "tichiel",
        tier: 3,
        name: "勉強用チンキ剤",
        effect: SkillEffect::RecordOnly,
        note: "[極・勉強用チンキ剤] スキルを選択 自身を含む、周辺のチームメイトのスキル攻撃力+10%（持続時間 30分）",
    },
    MasteryDef {
        id: "tichiel_m3_2",
        game_character_id: "tichiel",
        tier: 3,
        name: "赤い目の名薬",
        effect: SkillEffect::RecordOnly,
        note: "[極・赤い目の名薬] スキルを選択 自身を含む、周辺のチームメイトに「赤い目の名薬」バフを付与する（スキル攻撃力+20%、持続時間 5分） 「赤い目の名薬」バフが切れた後に「スキル減少」デバフのペナルティが発生する（スキル攻撃力-20%、60秒間） 再使用時に持続時間は初期化されない",
    },
    MasteryDef {
        id: "tichiel_m3_3",
        game_character_id: "tichiel",
        tier: 3,
        name: "遊び用チンキ剤",
        effect: SkillEffect::RecordOnly,
        note: "[極・遊び用チンキ剤] スキルを選択 自身を含む、周辺のチームメイトの移動速度(+2)／スキル命中率(+20%)が増加する（持続時間 30分）",
    },
    // --- yefnen
    MasteryDef {
        id: "yefnen_m1_1",
        game_character_id: "yefnen",
        tier: 1,
        name: "パイク特化",
        effect: SkillEffect::RecordOnly,
        note: "パイクシェイプ系スキルで後方攻撃時追加ダメージ+10%",
    },
    MasteryDef {
        id: "yefnen_m1_2",
        game_character_id: "yefnen",
        tier: 1,
        name: "アックス特化",
        effect: SkillEffect::RecordOnly,
        note: "アックスシェイプ系スキルで<ブレンド>がかかった状態の敵を攻撃すると、<ブレンド>の重複量が増加する <スレイ・アックス>と<クラッシュ・アックス>のチャージタイムが半減する",
    },
    MasteryDef {
        id: "yefnen_m1_3",
        game_character_id: "yefnen",
        tier: 1,
        name: "ウルミ特化",
        effect: SkillEffect::RecordOnly,
        note: "ウルミシェイプ系スキルで敵を攻撃すると、HPを回復する。 回復量公式:? 回復量上限:10万 回復クールタイム:1秒",
    },
    MasteryDef {
        id: "yefnen_m2_1",
        game_character_id: "yefnen",
        tier: 2,
        name: "安定した混合",
        effect: SkillEffect::RecordOnly,
        note: "<ブレンド>の能力を元のまま使用する。",
    },
    MasteryDef {
        id: "yefnen_m2_2",
        game_character_id: "yefnen",
        tier: 2,
        name: "膨張する混合",
        effect: SkillEffect::RecordOnly,
        note: "攻撃時、付与する<ブレンド>を減らす代わりに、付与した<ブレンド>の重複量が一定時間ごとに自動で増加する。",
    },
    MasteryDef {
        id: "yefnen_m2_3",
        game_character_id: "yefnen",
        tier: 2,
        name: "縮小する混合",
        effect: SkillEffect::RecordOnly,
        note: "攻撃時、付与する<ブレンド>を増やす代わりに、付与した<ブレンド>の重複量が一定時間ごとに自動で減少する。",
    },
    MasteryDef {
        id: "yefnen_m3_1",
        game_character_id: "yefnen",
        tier: 3,
        name: "安定した欠片",
        effect: SkillEffect::RecordOnly,
        note: "<フラグ>の能力をそのまま使う。",
    },
    MasteryDef {
        id: "yefnen_m3_2",
        game_character_id: "yefnen",
        tier: 3,
        name: "鋭い欠片",
        effect: SkillEffect::RecordOnly,
        note: "<フラグ>の爆発ダメージ量が減少する代わりに持続ダメージ量が増加する。",
    },
    MasteryDef {
        id: "yefnen_m3_3",
        game_character_id: "yefnen",
        tier: 3,
        name: "べたつく欠片",
        effect: SkillEffect::RecordOnly,
        note: "<フラグ>の持続ダメージ量が減少する代わりに、攻撃ダメージ減少効果を与える。",
    },
    MasteryDef {
        id: "yefnen_m4_1",
        game_character_id: "yefnen",
        tier: 4,
        name: "シャードバリア",
        effect: SkillEffect::RecordOnly,
        note: "<シャードスパイク>や<コンバインドシャード>を<シャードバリア>に変える。",
    },
    MasteryDef {
        id: "yefnen_m4_2",
        game_character_id: "yefnen",
        tier: 4,
        name: "シャードスパイク",
        effect: SkillEffect::RecordOnly,
        note: "<シャードバリア>や<コンバインドシャード>を<シャードスパイク>に変える。",
    },
    MasteryDef {
        id: "yefnen_m4_3",
        game_character_id: "yefnen",
        tier: 4,
        name: "コンバインドシャード",
        effect: SkillEffect::RecordOnly,
        note: "<シャードバリア>や<シャードスパイク>を<コンバインドシャード>に変える。",
    },
];

/// マスタリーのカタログ。
pub fn mastery_catalog() -> &'static [MasteryDef] {
    MASTERIES
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::{HashMap, HashSet};

    #[test]
    fn id_は一意でキャラは一覧にある() {
        let mut ids = HashSet::new();
        for d in MASTERIES {
            assert!(ids.insert(d.id), "id 重複: {}", d.id);
            assert!(
                crate::find_character(d.game_character_id).is_some(),
                "{} が一覧に無い",
                d.id
            );
        }
    }

    /// wiki のどのキャラの表も 1 段 3 択。
    #[test]
    fn どの段も3択() {
        let mut counts: HashMap<(&str, u8), usize> = HashMap::new();
        for d in MASTERIES {
            *counts.entry((d.game_character_id, d.tier)).or_default() += 1;
        }
        for ((cid, tier), n) in counts {
            assert_eq!(n, 3, "{cid} の M{tier}");
        }
    }

    /// id は `<キャラ>_m<段>_<1..3>`。並びが崩れるとアイコンの対応も崩れる。
    #[test]
    fn idは表の位置そのまま() {
        for d in MASTERIES {
            let prefix = format!("{}_m{}_", d.game_character_id, d.tier);
            assert!(d.id.starts_with(&prefix), "{}", d.id);
            let n: u8 = d.id[prefix.len()..].parse().unwrap_or(0);
            assert!((1..=3).contains(&n), "{}", d.id);
        }
    }

    /// アナイス以外の 18 キャラが入っている(wiki の Skill/アナイス にマスタリーの節が無い)。
    #[test]
    fn アナイス以外の18キャラが入っている() {
        let chars: HashSet<&str> = MASTERIES.iter().map(|d| d.game_character_id).collect();
        assert_eq!(chars.len(), 18);
        assert!(!chars.contains("anais"));
    }

    /// **マスタリー単体で無条件に効くもの**だけがここに載る。
    /// スキルの性能を書き換えるものは `character_skills.rs` の `mastery_overrides` が持つ
    /// (両方に持たせると二重に数える)。増やすときは wiki を読み直したうえで足す。
    #[test]
    fn 計算に入るのは12件() {
        let modeled: Vec<&str> = MASTERIES
            .iter()
            .filter(|d| d.effect.is_modeled())
            .map(|d| d.id)
            .collect();
        assert_eq!(
            modeled,
            [
                "boris_m1_1",   // 一閃 中ディレイ -5%
                "boris_m1_2",   // 斬撃 攻撃ダメージ +2%
                "boris_m2_3",   // シルバースカル優勝者 HACK/DEF +10%
                "boris_m4_1",   // 剣を扱う技術 HACK/DEF +10%
                "boris_m4_3",   // 冷酷で絶対的な審判者 攻撃ダメージ +2%
                "isolet_m1_3",  // ヨズレル 攻撃ダメージ +5%(バフ付与)
                "maximin_m1_3", // 怠惰 攻撃ダメージ +3%
                "maximin_m4_1", // 剣を扱う技術 HACK/DEF +10%
                "ranjie_m2_2",  // サイレンサー 攻撃ダメージ +3%
                "siberin_m2_1", // 槍術 攻撃ダメージ +5%
                "siberin_m4_2", // 不屈 攻撃ダメージ +5%(最大スタック)
                "siberin_m4_3", // 暴走 攻撃ダメージ +20%
            ]
        );
    }

    /// ボリスの段は wiki どおり M1〜M4。
    #[test]
    fn ボリスは4段() {
        let tiers: HashSet<u8> = MASTERIES
            .iter()
            .filter(|d| d.game_character_id == "boris")
            .map(|d| d.tier)
            .collect();
        let mut tiers: Vec<u8> = tiers.into_iter().collect();
        tiers.sort_unstable();
        assert_eq!(tiers, [1, 2, 3, 4]);
    }
}
