//! スキルの対象指定(単体 / 範囲)。
//!
//! 出典: wiki 各キャラの `Skill/<キャラ名>` ページ「スキル性能一覧」の対象指定列。
//! `tools/gamedata/skill_targets.py` が生成する。手で編集しない。

use domain::SkillTarget;

#[rustfmt::skip]
pub(crate) const SKILL_TARGETS: &[(&str, SkillTarget)] = &[
    ("anais_angry_pixie", SkillTarget::Area),  // アナイス 極・アングリーピクシー
    ("anais_cacophony", SkillTarget::Area),  // アナイス 極・カコフォニー
    ("anais_chain_lightning", SkillTarget::Single),  // アナイス 極・チェーンライトニング
    ("anais_crystal_attack", SkillTarget::Single),  // アナイス †極・結晶攻撃
    ("anais_crystal_sprinter", SkillTarget::Single),  // アナイス 極・クリスタルスプリンター
    ("anais_deathmoment", SkillTarget::Single),  // アナイス 極・デスモーメント
    ("anais_detonate", SkillTarget::Single),  // アナイス 極・ディトネート
    ("anais_dissonance", SkillTarget::Single),  // アナイス 極・ディソナンス
    ("anais_fairy_light", SkillTarget::Single),  // アナイス †極・フェアリーライト
    ("anais_fire_blast", SkillTarget::Single),  // アナイス 極・ファイアブラスト
    ("anais_flame_attack", SkillTarget::Single),  // アナイス †極・火炎攻撃
    ("anais_flare_field", SkillTarget::Area),  // アナイス 極・フレアフィールド
    ("anais_ice_age", SkillTarget::Area),  // アナイス 極・アイスエイジ
    ("anais_judgment_spin", SkillTarget::Area),  // アナイス 極・ジャッジメントスピン
    ("anais_lightning_attack", SkillTarget::Single),  // アナイス †極・電撃攻撃
    ("anais_mica_bear_step", SkillTarget::Area),  // アナイス 極・ミカベアステップ
    ("anais_ring_of_ice", SkillTarget::Area),  // アナイス 極・リングオブアイス
    ("anais_rucy_bear_step", SkillTarget::Area),  // アナイス 極・ルシベアステップ
    ("anais_rucy_even_bear", SkillTarget::Single),  // アナイス 極・熊連
    ("anais_rucy_footstep", SkillTarget::Area),  // アナイス 極・足踏み
    ("anais_strike", SkillTarget::Single),  // アナイス †極・叩く
    ("anais_tesla_coil", SkillTarget::Area),  // アナイス 極・テスラコイル
    ("anais_thrust", SkillTarget::Single),  // アナイス †極・突き
    ("benya_counter_hammer", SkillTarget::Area),  // ベンヤ 極・カウンターハンマー
    ("benya_curse_of_blood", SkillTarget::Area),  // ベンヤ 極・カース・オブ・ブラッド
    ("benya_death_chain", SkillTarget::Single),  // ベンヤ 極・デスチェーン
    ("benya_earth_dive", SkillTarget::Area),  // ベンヤ 極・アースダイブ
    ("benya_guillotine", SkillTarget::Area),  // ベンヤ 極・ギロチン
    ("benya_hell_gate", SkillTarget::Area),  // ベンヤ 極・ヘルゲート
    ("benya_meteor_soul", SkillTarget::Single),  // ベンヤ 極・ミーティアソウル
    ("benya_paul_hammer", SkillTarget::Area),  // ベンヤ 極・ポールハンマー
    ("benya_scythe_dancing", SkillTarget::Single),  // ベンヤ 極・サイズダンシング
    ("benya_sharp_hellfire", SkillTarget::Single),  // ベンヤ 極・シャープヘルファイア
    ("benya_soul_scream", SkillTarget::Area),  // ベンヤ 極・ソウルスクリーム
    ("benya_soul_steal", SkillTarget::Area),  // ベンヤ 極・ソウルスチール
    ("benya_space_cutting", SkillTarget::Area),  // ベンヤ 極・スペースカッティング
    ("benya_strike_blow", SkillTarget::Single),  // ベンヤ 極・ストライクブロー
    ("boris_blur_sword", SkillTarget::Single),  // ボリス 極・残影斬
    ("boris_continuous", SkillTarget::Single),  // ボリス 極・連
    ("boris_crash_bomb", SkillTarget::Area),  // ボリス 極・クラッシュボム
    ("boris_explosion", SkillTarget::Area),  // ボリス 極・爆
    ("boris_frozen_break", SkillTarget::Area),  // ボリス 極・フローズンブレイク
    ("boris_frozen_sleigh", SkillTarget::Area),  // ボリス 極・フローズンスレイ
    ("boris_gracia", SkillTarget::Area),  // ボリス 極・グラシア
    ("boris_horizontal_sword", SkillTarget::Single),  // ボリス †極・横斬り
    ("boris_ice_attack_sword", SkillTarget::Single),  // ボリス 極・氷撃斬
    ("boris_ice_break", SkillTarget::Single),  // ボリス †極・アイスブレイク
    ("boris_ice_fog", SkillTarget::Area),  // ボリス 極・アイスフォグ
    ("boris_ice_missile", SkillTarget::Single),  // ボリス 極・アイスミサイル
    ("boris_icing_earrings", SkillTarget::Area),  // ボリス 極・アイシングピアス
    ("boris_inherited", SkillTarget::Area),  // ボリス 極・インヘリテッド
    ("boris_smash_crusher", SkillTarget::Area),  // ボリス 極・スマッシュクラッシャー
    ("boris_vertical_sword", SkillTarget::Single),  // ボリス †極・縦斬り
    ("chloe_air_beat", SkillTarget::Single),  // クロエ †極・エアビート
    ("chloe_electric_ball", SkillTarget::Area),  // クロエ 極・エレクトリックボール
    ("chloe_extraction", SkillTarget::Area),  // クロエ 極・エクストーション
    ("chloe_fire_arrow", SkillTarget::Single),  // クロエ 極・ファイヤーアロー
    ("chloe_fire_ball", SkillTarget::Area),  // クロエ 極・ファイヤーボール
    ("chloe_fire_beat", SkillTarget::Single),  // クロエ †極・ファイヤービート
    ("chloe_gast", SkillTarget::Single),  // クロエ 極・ガスト
    ("chloe_gravity", SkillTarget::Area),  // クロエ 極・グラビティ
    ("chloe_ice_beat", SkillTarget::Single),  // クロエ †極・アイスビート
    ("chloe_ice_missile", SkillTarget::Single),  // クロエ 極・アイスミサイル
    ("chloe_icicle_rain", SkillTarget::Area),  // クロエ 極・アイシクルレイン
    ("chloe_lightning_beat", SkillTarget::Single),  // クロエ †極・ライトニングビート
    ("chloe_mega_blaze", SkillTarget::Area),  // クロエ 極・メガブレイズ
    ("chloe_meteor_strike", SkillTarget::Area),  // クロエ 極・メテオストライク
    ("chloe_radial_thunder", SkillTarget::Area),  // クロエ 極・ラディアルサンダー
    ("chloe_sand_storm", SkillTarget::Area),  // クロエ 極・サンドストーム
    ("chloe_snow_flake", SkillTarget::Area),  // クロエ 極・スノーフレーク
    ("chloe_square_shock", SkillTarget::Area),  // クロエ 極・スクエアショック
    ("chloe_static_field", SkillTarget::Area),  // クロエ 極・スタティックフィールド
    ("chloe_stone_arrow", SkillTarget::Single),  // クロエ 極・ストーンアロー
    ("chloe_stone_beat", SkillTarget::Single),  // クロエ †極・ストーンビート
    ("chloe_thunder_strike", SkillTarget::Single),  // クロエ 極・サンダーストライク
    ("chloe_tornado", SkillTarget::Area),  // クロエ 極・トルネード
    ("chloe_vacuumize", SkillTarget::Area),  // クロエ 極・バキューマイズ
    ("isaac_backfist_strike", SkillTarget::Single),  // イサック †極・裏拳打ち
    ("isaac_blasting_blow", SkillTarget::Area),  // イサック 極・ブラスティングブロー
    ("isaac_break_through", SkillTarget::Area),  // イサック 極・ブレイクスルー
    ("isaac_chris_cross", SkillTarget::Single),  // イサック 極・連打
    ("isaac_demise_furious", SkillTarget::Single),  // イサック 極・滅神乱舞
    ("isaac_destrudo", SkillTarget::Area),  // イサック 極・発勁・乱
    ("isaac_double_kick", SkillTarget::Single),  // イサック †極・ダブルキック
    ("isaac_energy_field", SkillTarget::Area),  // イサック 極・エネルギーフィールド
    ("isaac_energy_punch", SkillTarget::Single),  // イサック 極・発勁
    ("isaac_energy_wave", SkillTarget::Area),  // イサック 極・龍点穴
    ("isaac_forefist_punch", SkillTarget::Single),  // イサック †極・正拳突き
    ("isaac_jab", SkillTarget::Single),  // イサック †極・ジャブ
    ("isaac_jab_punch", SkillTarget::Single),  // イサック †極・刻み突き
    ("isaac_lion_fear", SkillTarget::Area),  // イサック 極・獅子吼
    ("isaac_power_punch", SkillTarget::Single),  // イサック 極・バーストマグナム
    ("isaac_slam_bang", SkillTarget::Single),  // イサック 極・スラムバン
    ("isaac_straight", SkillTarget::Single),  // イサック †極・ストレート
    ("isolet_back_blade", SkillTarget::Area),  // イソレット 極・バックブレイド
    ("isolet_butt", SkillTarget::Single),  // イソレット †極・突き
    ("isolet_circle", SkillTarget::Area),  // イソレット 極・円
    ("isolet_continuous", SkillTarget::Single),  // イソレット 極・連
    ("isolet_dash_blade", SkillTarget::Area),  // イソレット 極・ダッシュブレイド
    ("isolet_devine_beat", SkillTarget::Single),  // イソレット †極・ディバインビート
    ("isolet_gale_sword", SkillTarget::Area),  // イソレット 極・烈風斬
    ("isolet_gloria", SkillTarget::Single),  // イソレット 極・グロリア
    ("isolet_gravity_field", SkillTarget::Area),  // イソレット 極・グラビティフィールド
    ("isolet_holy_bird", SkillTarget::Area),  // イソレット 極・ホーリーバード
    ("isolet_holy_light", SkillTarget::Area),  // イソレット 極・ホーリーライト
    ("isolet_holy_phoenix", SkillTarget::Area),  // イソレット 極・ホーリーフェニックス
    ("isolet_horizontal_sword", SkillTarget::Single),  // イソレット †極・横切り
    ("isolet_sonic_wave", SkillTarget::Area),  // イソレット 極・ソニックウェーブ
    ("isolet_storm_blade", SkillTarget::Single),  // イソレット 極・ストームブレード
    ("isolet_storm_blast", SkillTarget::Area),  // イソレット 極・ストームブラスト
    ("isolet_storm_dance", SkillTarget::Area),  // イソレット 極・ストームダンス
    ("isolet_vacuum_sword", SkillTarget::Area),  // イソレット 極・真空斬
    ("isolet_whirl_wind", SkillTarget::Single),  // イソレット 極・かまいたち
    ("isolet_wind_spear", SkillTarget::Area),  // イソレット 極・ウィンドスピア
    ("isolet_zone_burst", SkillTarget::Area),  // イソレット 極・ゾーンバースト
    ("ispin_counter_spear", SkillTarget::Area),  // イスピン 極・カウンタースピア
    ("ispin_double_cross_slash", SkillTarget::Area),  // イスピン 極・クロスブランディング
    ("ispin_gale_butt", SkillTarget::Single),  // イスピン 極・疾風突
    ("ispin_grand_cross", SkillTarget::Single),  // イスピン 極・グランドクロス
    ("ispin_killing", SkillTarget::Single),  // イスピン 極・殺
    ("ispin_over_cut", SkillTarget::Single),  // イスピン †極・オーバーカット
    ("ispin_ren", SkillTarget::Single),  // イスピン 極・連
    ("ispin_sanfamu", SkillTarget::Area),  // イスピン 極・散花舞
    ("ispin_scratch", SkillTarget::Single),  // イスピン †極・スクラッチ
    ("ispin_step_in", SkillTarget::Single),  // イスピン †極・ステップイン
    ("joshua_death_claw", SkillTarget::Single),  // ジョシュア †極・デスクロー
    ("joshua_finale", SkillTarget::Single),  // ジョシュア 極・フィナーレ
    ("joshua_ghost_burst", SkillTarget::Single),  // ジョシュア 極・ゴーストバースト
    ("joshua_iron_mist", SkillTarget::Area),  // ジョシュア 極・黒霧雲
    ("joshua_ruin", SkillTarget::Area),  // ジョシュア 極・ルイン
    ("joshua_shadow_vision", SkillTarget::Single),  // ジョシュア 極・メンティサイド
    ("joshua_soul_burst", SkillTarget::Area),  // ジョシュア 極・ソウルバースト
    ("joshua_soul_grab", SkillTarget::Area),  // ジョシュア 極・ソウルグラブ
    ("joshua_soul_slayer", SkillTarget::Area),  // ジョシュア 極・ソウルスレイヤー
    ("joshua_staccato", SkillTarget::Single),  // ジョシュア 極・スタッカート
    ("joshua_sting", SkillTarget::Single),  // ジョシュア †極・スティング
    ("joshua_vertical_infinity", SkillTarget::Area),  // ジョシュア 極・バーティカルインフィニティ
    ("leeche_anarose_skill_5", SkillTarget::Area),  // リーチェ 極・クラヴァータ
    ("leeche_anarose_skill_6", SkillTarget::Single),  // リーチェ 極・テセーレ
    ("leeche_armor_of_evil_skill_11", SkillTarget::Area),  // リーチェ 極・スピロ
    ("leeche_armor_of_evil_skill_12", SkillTarget::Area),  // リーチェ 極・リフィラーレ
    ("leeche_armor_of_evil_skill_13", SkillTarget::Area),  // リーチェ 極・アーゴグロッソ
    ("leeche_armor_of_evil_skill_2", SkillTarget::Area),  // リーチェ 極・圧殺
    ("leeche_armor_of_evil_skill_3", SkillTarget::Single),  // リーチェ 極・絞殺
    ("leeche_armor_of_evil_skill_8", SkillTarget::Area),  // リーチェ 極・爆気
    ("leeche_armor_of_evil_skill_9", SkillTarget::Area),  // リーチェ 極・酸化
    ("leeche_monpureine_skill_1", SkillTarget::Single),  // リーチェ †極・トンド
    ("leeche_monpureine_skill_10", SkillTarget::Area),  // リーチェ 極・モリネト
    ("leeche_monpureine_skill_11", SkillTarget::Area),  // リーチェ 極・モリネトポテンテ
    ("leeche_monpureine_skill_12", SkillTarget::Area),  // リーチェ 極・モリネトアビーレ
    ("leeche_monpureine_skill_19", SkillTarget::Area),  // リーチェ 極・ペンデュラム投擲
    ("leeche_monpureine_skill_2", SkillTarget::Single),  // リーチェ †極・フェンデンテ
    ("leeche_monpureine_skill_21", SkillTarget::Area),  // リーチェ 極・回避起動
    ("leeche_monpureine_skill_3", SkillTarget::Single),  // リーチェ †極・プンタ
    ("leeche_monpureine_skill_4", SkillTarget::Single),  // リーチェ 極・アレグロ
    ("leeche_monpureine_skill_5", SkillTarget::Single),  // リーチェ 極・アレグロ・ディ・モルト
    ("leeche_monpureine_skill_6", SkillTarget::Single),  // リーチェ 極・アレグレット
    ("leeche_monpureine_skill_7", SkillTarget::Single),  // リーチェ 極・フォルテ
    ("leeche_monpureine_skill_8", SkillTarget::Single),  // リーチェ 極・フォルティッシモ
    ("leeche_monpureine_skill_9", SkillTarget::Single),  // リーチェ 極・メゾフォルテ
    ("leeche_runaway_skill_2", SkillTarget::Area),  // リーチェ 極・血を流す槍
    ("lucian_butt", SkillTarget::Single),  // ルシアン †極・突き
    ("lucian_circle", SkillTarget::Area),  // ルシアン 極・円
    ("lucian_continuous", SkillTarget::Single),  // ルシアン 極・連
    ("lucian_crescent_slash", SkillTarget::Area),  // ルシアン 極・三日月斬り
    ("lucian_fei", SkillTarget::Single),  // ルシアン 極・飛
    ("lucian_flying_burst", SkillTarget::Area),  // ルシアン 極・飛連破
    ("lucian_horizontal_sword", SkillTarget::Single),  // ルシアン †極・横斬り
    ("lucian_killing", SkillTarget::Single),  // ルシアン 極・殺
    ("lucian_streak", SkillTarget::Single),  // ルシアン 極・連撃
    ("lucian_sylph_cutter", SkillTarget::Area),  // ルシアン 極・シルフカッター
    ("lucian_vertical_sword", SkillTarget::Single),  // ルシアン †極・縦斬り
    ("lucian_vortex", SkillTarget::Single),  // ルシアン 極・ヴォーテックス
    ("lucian_waltz", SkillTarget::Single),  // ルシアン 極・円舞
    ("lucian_warriors_dance", SkillTarget::Single),  // ルシアン 極・無双乱舞
    ("lucian_whirlwind_sword", SkillTarget::Single),  // ルシアン 極・旋風斬
    ("lucian_wind_slice", SkillTarget::Single),  // ルシアン 極・ウィンドスライス
    ("maximin_air_break", SkillTarget::Single),  // マキシミン †極・エアブレイク
    ("maximin_attracted_sword", SkillTarget::Single),  // マキシミン †極・引き付け斬り
    ("maximin_continuous", SkillTarget::Single),  // マキシミン 極・連
    ("maximin_explosion", SkillTarget::Area),  // マキシミン 極・爆
    ("maximin_mistral_blade", SkillTarget::Area),  // マキシミン 極・ミストラルブレード
    ("maximin_moonlight_sword", SkillTarget::Single),  // マキシミン 極・閃花月光斬
    ("maximin_roll_hash", SkillTarget::Area),  // マキシミン 極・ロールハッシュ
    ("maximin_storm_eye", SkillTarget::Single),  // マキシミン 極・爆風の目
    ("maximin_sword", SkillTarget::Single),  // マキシミン †極・スラッシュ
    ("maximin_sylph_lance", SkillTarget::Area),  // マキシミン 極・シルフランス
    ("maximin_wind_slice", SkillTarget::Single),  // マキシミン 極・ウィンドスライス
    ("maximin_wind_storm", SkillTarget::Area),  // マキシミン 極・ウィンドストーム
    ("maximin_wind_tooth_knife", SkillTarget::Single),  // マキシミン 極・風牙刀
    ("maximin_zan", SkillTarget::Single),  // マキシミン 極・斬
    ("mira_bite_viper", SkillTarget::Single),  // ミラ 極・バイトヴァイパー
    ("mira_card_spray_a", SkillTarget::Area),  // ミラ 極・カードスプレー A
    ("mira_cool_whip", SkillTarget::Single),  // ミラ †極・クールウィップ
    ("mira_crazy_viper", SkillTarget::Area),  // ミラ 極・クレージーヴァイパー
    ("mira_crimson_shooter", SkillTarget::Area),  // ミラ 極・紅い射手の砲撃
    ("mira_dancing_viper", SkillTarget::Single),  // ミラ 極・ダンシングヴァイパー
    ("mira_dew_storm", SkillTarget::Area),  // ミラ 極・ダガーストーム
    ("mira_dirty_strike", SkillTarget::Single),  // ミラ 極・ダーティーストライク
    ("mira_hard_whip", SkillTarget::Single),  // ミラ †極・ハードウィップ
    ("mira_hit_whip", SkillTarget::Single),  // ミラ †極・ヒットウィップ
    ("mira_mad_bite_viper", SkillTarget::Area),  // ミラ 極・マッドヴァイパー
    ("mira_whip", SkillTarget::Single),  // ミラ †極・ウィップ
    ("nayatorei_assault", SkillTarget::Area),  // ナヤトレイ 極・襲撃
    ("nayatorei_avatar", SkillTarget::Area),  // ナヤトレイ 極・分身乱撃
    ("nayatorei_back_stab", SkillTarget::Single),  // ナヤトレイ 極・バックステップ
    ("nayatorei_cross_thrust", SkillTarget::Single),  // ナヤトレイ †極・クロススラスト
    ("nayatorei_dance", SkillTarget::Area),  // ナヤトレイ 極・花蝶乱舞
    ("nayatorei_dual_hit", SkillTarget::Single),  // ナヤトレイ †極・デュアルヒット
    ("nayatorei_flash", SkillTarget::Area),  // ナヤトレイ 極・忍術 閃
    ("nayatorei_heart", SkillTarget::Single),  // ナヤトレイ 極・心
    ("nayatorei_mausoleum", SkillTarget::Single),  // ナヤトレイ 極・狂猫
    ("nayatorei_ren", SkillTarget::Single),  // ナヤトレイ 極・連
    ("nayatorei_shuriken", SkillTarget::Area),  // ナヤトレイ 極・手裏剣打ち
    ("nayatorei_slash", SkillTarget::Single),  // ナヤトレイ †極・スラッシュ
    ("nayatorei_wide_assault", SkillTarget::Area),  // ナヤトレイ 極・無差別的な襲撃
    ("nocturne_buster_launcher", SkillTarget::Single),  // ノクターン 極・バスターランチャー
    ("nocturne_cluster_rocket", SkillTarget::Area),  // ノクターン 極・クラスターロケット
    ("nocturne_laser_canon", SkillTarget::Area),  // ノクターン 極・レーザーカノン
    ("nocturne_launcher", SkillTarget::Single),  // ノクターン †極・ランチャー
    ("nocturne_lightning_bomb", SkillTarget::Area),  // ノクターン 極・ライトニングボム
    ("nocturne_magnetic_force", SkillTarget::Area),  // ノクターン 極・マグネティックフォース
    ("nocturne_plasma_canon", SkillTarget::Area),  // ノクターン 極・プラズマカノン
    ("nocturne_quantum_nuclear", SkillTarget::Area),  // ノクターン 極・クアンタムニュークリア
    ("nocturne_satellite_canon", SkillTarget::Area),  // ノクターン 極・サテライトカノン
    ("nocturne_shining_laser", SkillTarget::Area),  // ノクターン 極・シャイニングレーザー
    ("ranjie_crazy_shot", SkillTarget::Single),  // ランジエ 極・クレイジーショット
    ("ranjie_dual_shot", SkillTarget::Single),  // ランジエ †極・デュアルショット
    ("ranjie_gunshot", SkillTarget::Single),  // ランジエ †極・射撃
    ("ranjie_hard_shot", SkillTarget::Single),  // ランジエ †極・ハードショット
    ("ranjie_ice_pierce_shot", SkillTarget::Single),  // ランジエ 極・アイスピアスショット
    ("ranjie_ice_shot", SkillTarget::Single),  // ランジエ 極・アイスショット
    ("ranjie_magic_bullet", SkillTarget::Single),  // ランジエ †極・魔弾
    ("ranjie_magical_dual_shot", SkillTarget::Single),  // ランジエ †極・マジカルデュアルショット
    ("ranjie_magical_hard_shot", SkillTarget::Single),  // ランジエ †極・マジカルハードショット
    ("ranjie_misty_shot", SkillTarget::Area),  // ランジエ 極・ミスティーショット
    ("ranjie_multi_shot", SkillTarget::Area),  // ランジエ 極・マルチショット
    ("ranjie_piercing_shot", SkillTarget::Area),  // ランジエ 極・ピアシングショット
    ("roamini_carse_flame", SkillTarget::Single),  // ロアミニ 極・カース・フレイム
    ("roamini_curse_nova", SkillTarget::Area),  // ロアミニ 極・カース・ノヴァ
    ("roamini_darkness_flare", SkillTarget::Single),  // ロアミニ †極・ダークネス・フレア
    ("roamini_darkness_gazer", SkillTarget::Area),  // ロアミニ 極・ダークネス・ゲイザー
    ("roamini_mastary1_2", SkillTarget::Area),  // ロアミニ 極・ベノムノヴァ
    ("roamini_mastary2_3", SkillTarget::Single),  // ロアミニ 極・怨恨
    ("roamini_mastary2_4", SkillTarget::Area),  // ロアミニ 極・カース・エンド
    ("roamini_mastary3_2", SkillTarget::Area),  // ロアミニ 極・逃走
    ("roamini_mastary3_3", SkillTarget::Area),  // ロアミニ 極・浸透
    ("roamini_poison_dart", SkillTarget::Single),  // ロアミニ †極・ポイズンダーツ
    ("roamini_poison_mist", SkillTarget::Area),  // ロアミニ 極・ポイズン・ミスト
    ("siberin_beat_down", SkillTarget::Single),  // シベリン †極・ビートダウン
    ("siberin_bombing", SkillTarget::Area),  // シベリン 極・爆撃
    ("siberin_brandy", SkillTarget::Single),  // シベリン †極・ブランディ
    ("siberin_continuous_thrust", SkillTarget::Single),  // シベリン 極・連突き
    ("siberin_even_fly", SkillTarget::Single),  // シベリン 極・飛連
    ("siberin_red_dragon_climb", SkillTarget::Area),  // シベリン 極・紅龍登天
    ("siberin_red_dragon_strike", SkillTarget::Single),  // シベリン 極・紅龍連撃
    ("siberin_throw_dragon", SkillTarget::Area),  // シベリン 極・投龍
    ("siberin_thrust", SkillTarget::Single),  // シベリン †極・突き
    ("siberin_turning", SkillTarget::Single),  // シベリン †極・ターニング
    ("siberin_twin_dragon_slash", SkillTarget::Single),  // シベリン 極・双龍閃
    ("siberin_twin_dragon_strike", SkillTarget::Single),  // シベリン 極・双龍撃
    ("tichiel_aurora_wall", SkillTarget::Area),  // ティチエル 極・オーロラウォール
    ("tichiel_beating", SkillTarget::Single),  // ティチエル 極・乱打
    ("tichiel_blade_wall", SkillTarget::Area),  // ティチエル 極・ブレイドウォール
    ("tichiel_blizzard", SkillTarget::Area),  // ティチエル 極・ブリザード
    ("tichiel_break_armor", SkillTarget::Area),  // ティチエル 極・ブレイクアーマー
    ("tichiel_burning_air", SkillTarget::Area),  // ティチエル 極・バーニングエア
    ("tichiel_calling_thunder", SkillTarget::Area),  // ティチエル 極・コーリングサンダー
    ("tichiel_cold_snap", SkillTarget::Area),  // ティチエル 極・コールドスナップ
    ("tichiel_fire_arrow", SkillTarget::Single),  // ティチエル 極・ファイヤーアロー
    ("tichiel_fire_ball", SkillTarget::Area),  // ティチエル 極・ファイヤーボール
    ("tichiel_frost_coating", SkillTarget::Area),  // ティチエル 極・フロストコーティング
    ("tichiel_giga_blaze", SkillTarget::Area),  // ティチエル 極・ギガブレイズ
    ("tichiel_holy_bolt", SkillTarget::Single),  // ティチエル 極・ホーリーボルト
    ("tichiel_ice_missile", SkillTarget::Single),  // ティチエル 極・アイスミサイル
    ("tichiel_lightning_bolt", SkillTarget::Single),  // ティチエル 極・ライトニングボルト
    ("tichiel_smash", SkillTarget::Single),  // ティチエル †極・スマッシュ
    ("tichiel_sparkling_kite", SkillTarget::Single),  // ティチエル 極・スパークリングカイト
    ("tichiel_sunrise", SkillTarget::Area),  // ティチエル 極・サンライズ
    ("tichiel_twinkle", SkillTarget::Single),  // ティチエル †極・トゥインクル
    ("yefnen_continuous", SkillTarget::Single),  // イェフネン 極・連
    ("yefnen_continuous_axe", SkillTarget::Single),  // イェフネン 極・連・アックス
    ("yefnen_continuous_chisel", SkillTarget::Single),  // イェフネン 極・連・チゼル
    ("yefnen_continuous_pike", SkillTarget::Single),  // イェフネン 極・連・パイク
    ("yefnen_continuous_urumi", SkillTarget::Single),  // イェフネン 極・連・ウルミ
    ("yefnen_crash", SkillTarget::Area),  // イェフネン 極・クラッシュ
    ("yefnen_crash_axe", SkillTarget::Area),  // イェフネン 極・クラッシュ・アックス
    ("yefnen_crash_chisel", SkillTarget::Area),  // イェフネン 極・クラッシュ・チゼル
    ("yefnen_crash_pike", SkillTarget::Area),  // イェフネン 極・クラッシュ・パイク
    ("yefnen_crash_urumi", SkillTarget::Area),  // イェフネン 極・クラッシュ・ウルミ
    ("yefnen_explosion", SkillTarget::Area),  // イェフネン 極・爆
    ("yefnen_explosion_axe", SkillTarget::Area),  // イェフネン 極・爆・アックス
    ("yefnen_explosion_chisel", SkillTarget::Area),  // イェフネン 極・爆・チゼル
    ("yefnen_explosion_pike", SkillTarget::Area),  // イェフネン 極・爆・パイク
    ("yefnen_explosion_urumi", SkillTarget::Area),  // イェフネン 極・爆・ウルミ
    ("yefnen_slay", SkillTarget::Single),  // イェフネン 極・スレイ
    ("yefnen_slay_axe", SkillTarget::Single),  // イェフネン 極・スレイ・アックス
    ("yefnen_slay_chisel", SkillTarget::Single),  // イェフネン 極・スレイ・チゼル
    ("yefnen_slay_pike", SkillTarget::Single),  // イェフネン 極・スレイ・パイク
    ("yefnen_slay_urumi", SkillTarget::Single),  // イェフネン 極・スレイ・ウルミ
];
